# Python Fundamentos

## Lista de Exercícios

1. Crie um script Python que leia o nome de uma pessoa e mostre uma mensagem de boas vindas de acordo com o valor digitado.

In [2]:
print('====== DESAFIO 01 ======')
nome = input('Qual é o seu nome? ')
print('Olá ' + nome + '! Prazer em te conhecer!') # se usar vírgulas ao invés de +, haverá espaços.

====== DESAFIO 01 ======
Qual é o seu nome? Icaro
Olá Icaro! Prazer em te conhecer!


2. Crie um script Python que leia o ano, o dia e o mês de nascimento de uma pessoa e mostre uma mensagem com a data formatada.

In [7]:
print('====== DESAFIO 02 ======')
dia = input('Dia: ')
mes = input('Mês: ')
ano = input('Ano: ')
print('Você nasceu no dia ' + dia + ' de ' + mes + ' de ' + ano + '. Correto?')

====== DESAFIO 02 ======
Dia: 14
Mês: Fev
Ano: 1984
Você nasceu no dia 14 de Fev de 1984. Correto?


3. Crie um script Python que leia dis números e tente mostrar a soma entre eles.

In [9]:
num1 = int(input('Digite um valor: '))
num2 = int(input('Digite outro valor: '))
soma = num1 + num2
print('A soma entre', num1, 'e', num2, 'é igual a', soma, '!') # tipos diferentes exige vírgula ao invés de +

Digite um valor: 5
Digite outro valor: 9
A soma entre 5 e 9 é igual a 14 !


4. Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas as informações possíveis sobre ele.

In [10]:
msg = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type(msg)}')
print(f'Só tem espaços? {msg.isspace()}')
print(f'É um número? {msg.isnumeric()}')
print(f'É alfabético? {msg.isalpha()}')
print(f'É alfanumérico? {msg.isalnum()}')
print(f'Está em maiúsculas? {msg.isupper()}')
print(f'Está em minúsculas? {msg.islower()}')
print(f'Está capitalizada? {msg.istitle()}')
# obs.: msg é um objeto que aceita métodos da sua classe do tipo str

Digite algo: Programador
O tipo primitivo desse valor é <class 'str'>
Só tem espaços? False
É um número? False
É alfabético? True
É alfanumérico? True
Está em maiúsculas? False
Está em minúsculas? False
Está capitalizada? True


5. Faça um programa que leia um número inteiro e mostre seu sucessor e seu antecessor.

In [12]:
num = int(input('Digite um número: '))
print(f'Analizando o valor {num}, seu antecessor é {num-1} e seu sucessor é {num+1}')

Digite um número: 2
Analizando o valor 2, seu antecessor é 1 e seu sucessor é 3


6. Crie um algoritmo que leia um número inteiro e mostre seu dobro, seu triplo e sua raíz quadrada.

In [15]:
num = int(input('Digite um número: '))

print(f'O dobro de {num} vale {2*num}.')
print(f'O triplo de {num} vale {3*num}.')
print(f'A raíz quadrada de {num} é igual a {num**(1/2):.2f}.')

Digite um número: 85
O dobro de 85 vale 170.
O triplo de 85 vale 255.
A raíz quadrada de 85 é igual a 9.22.


7. Desenvolva um programa que leia as duas notas de um aluno, calcule e mostre a sua média.

In [17]:
n1 = float(input('Primeira nota do aluno: '))
n2 = float(input('Segunda nota do aluno: '))
print(f'A média entre {n1} e {n2} é igual a {(n1 + n2)/2:.1f}')

Primeira nota do aluno: 5.5
Segunda nota do aluno: 2
A média entre 5.5 e 2.0 é igual a 3.8


8. Escreva um programa que leia um valor em metros e o exiba convertido em centímetros e milímetros.

In [20]:
dist = float(input('Um distância em metros: '))
print(f'''A medida de {dist:.1f}m corresponde a
{dist/1000}km
{dist/100}hm
{dist/10}dam
{dist*10:.0f}dm
{dist*100:.0f}cm
{dist*1000:.0f}mm''')

Um distância em metros: 3
A medida de 3.0m corresponde a
0.003km
0.03hm
0.3dam
30dm
300cm
3000mm


9. Faça um exercício que leia um número inteiro qualquer e mostre na tela a sua tabuada.

In [22]:
num = int(input('Digite um número para ver a sua tabuada: '))
print(f'''------------
{num} x  1 = {num}
{num} x  2 = {num*2}
{num} x  3 = {num*3}
{num} x  4 = {num*4}
{num} x  5 = {num*5}
{num} x  6 = {num*6}
{num} x  7 = {num*7}
{num} x  8 = {num*8}
{num} x  9 = {num*9}
{num} x 10 = {num*10}
============''')

Digite um número para ver a sua tabuada: 6
------------
6 x  1 = 6
6 x  2 = 12
6 x  3 = 18
6 x  4 = 24
6 x  5 = 30
6 x  6 = 36
6 x  7 = 42
6 x  8 = 48
6 x  9 = 54
6 x 10 = 60


10. Crie um programa que leia quanto dinheiro uma pessoa tenha na carteira e mostre quantos dólares ela pode comprar.
</br>
<code>cotação: US$1,00 = R$3,27</code> 

In [24]:
real = float(input('Quanto dinheiro você tem na carteira: R$'))
dolar = real/3.27
print(f'com R${real} você pode comprar US${dolar:.2f}')

Quanto dinheiro você tem na carteira: R$19.88
com R$19.88 você pode comprar US$6.08


11. Faça um programa que leia a altura e a largura de uma parede em metros, calcule a área e a quantidade de tinta necessária para pintá-la, sabendo que cada litro de tinta pinta uma área de 2m².

In [1]:
largura = float(input('Largura da parede: '))
altura = float(input('Altura da parede: '))
area = largura * altura
litros_de_tinta = area/2

print(f'Sua parede tem dimensão de {largura}x{altura} e sua área é de {area}m².')
print(f'Para pintar essa parede, você precisará de {litros_de_tinta}l de tinta.')

Largura da parede: 2.5
Altura da parede: 1.75
Sua parede tem dimensão de 2.5x1.75 e sua área é de 4.375m².
Para pintar essa parede, você precisará de 2.1875l de tinta.


12. Faça um algoritmo que leia o preço de um produto e mostre seu novo preço com 5% de desconto.

In [3]:
preco = float(input('Qual o preço do produto? R$'))
novo_preco = 0.95*preco

print(f'O produto que custava R${preco}, na promoção com 5% de desconto vai custar R${novo_preco:.2f}.')

Qual o preço do produto? R$123.95
O produto que custava R$123.95, na promoção com 5% de desconto vai custar R$117.75


13. Faça um algoritmo que leia o salário de um fincionário e mostre seu novo salário com 15% de aumento.

In [4]:
salario = float(input('Qual é o salário do funcionário? R$'))
novo_salario = 1.15*salario

print(f'Um funcionário que ganhava R${salario}, com 15% de aumento, passa a receber {novo_salario:.2f}.')

Qual é o salário do funcionário? R$4319.43
Um funcionário que ganhava R$4319.43, com 15% de aumento, passa a receber 4967.34.


14. Escreva um programa que converta uma temperatura digitando em graus Celsius e converta para graus Fahrenheit.

In [6]:
temp_c = float(input('Informe a temperatura em °C: '))
temp_f = 9*temp_c/5 + 32

print(f'A temperatura de {temp_c}°C corresponde a {temp_f}°F.')

Informe a temperatura em °C: 31.5
A temperatura de 31.5°C corresponde a 88.7°F.


15. Escreva um programa que pergunte a quantidade de Km percorridos por um carro alugado e a quantidade de dias pelos quais ele foi alugado. Calcule o preço a pagar, sabendo que o carro custa RS60 por dia e RS0,15 por Km rodado.

In [8]:
dias = int(input('Quantos dias alugado? '))
km = float(input('Quantos Km rodados? '))
total = 60*dias + 0.15*km

print(f'O total a pagar é de {total:.2f}.')

Quantos dias alugado? 8
Quantos Km rodados? 720
O total a pagar é de 588.00.


16. Crie um programa que leia o nome completo de uma pessoa e mostre:
- Nome com todas as letras em maiúsculo
- Nome com todas as letras em minúsculo
- Quantas letras ao todo (sem considerar espaços)?
- Quantas letras tem o primeiro nome?

In [1]:
nome = input('Digite seu nome completo: ').strip() #retira espaços do início e do fim
print(nome.upper())
print(nome.lower())

print(f'O nome completo possui {len(nome) - nome.count(" ")} letras')
print(f'O primeiro nome possui {nome.find(" ")} letras') #não conta as letras mas a posição do primeiro espaço

# outra forma:
dividido = nome.split()
juntado = ''.join(dividido)
# print(f'O nome completo possui {len(juntado)} letras')
# print(f'O primeiro nome é {dividido[0]} e ele possui {len(dividido[0])} letras')

Digite seu nome completo:    Icaro Duarte    Martins  
ICARO DUARTE    MARTINS
icaro duarte    martins
O nome completo possui 18 letras
O primeiro nome possui 5 letras


17. Faça um programa que leia um número de 0 a 9999 e mostre na tela cada um dos dígitos separados.

In [7]:
num = int(input('Digite um número de 0 a 9999: '))
u = num // 1 % 10 #o resto é o próprio número
d = num // 10 % 10
c = num // 100 % 10
m = num // 1000 % 10

print(f'Unidade: {u}')
print(f'Dezena: {d}')
print(f'Centena: {c}')
print(f'Milhar: {m}')

Digite um número de 0 a 9999: 1234
Unidade: 4
Dezena: 3
Centena: 2
Milhar: 1


In [62]:
# outra forma:

num = f'{input("Digite um número de 0 a 9999: "):0>4}'
# num = f'{num:0>4}' #acrescenta caracteres '0's ao número alinhado à direita

print(f'Unidade: {num[3]}')
print(f'Dezena: {num[2]}')
print(f'Centena: {num[1]}')
print(f'Milhar: {num[0]}')

Digite um número de 0 a 9999: 1984
Unidade: 4
Dezena: 8
Centena: 9
Milhar: 1


18. Crie um programa que leia o nome de uma cidade e diga se ela começa ou não com o nome 'Santo'?

In [66]:
cid = input('Em que cidade você nasceu? ').strip()

print(f'{cid[:5].upper() == "SANTO"}')

Em que cidade você nasceu? Santo Amaro
True


19. Crie um programa que leia o nome de uma pessoa e diga se ela tem 'Silva' no nome.

In [74]:
nome = input('Digite seu nome completo: ').strip()

print('silva' in nome.lower())

Digite seu nome completo: Alisson Silva
True


20. Faça um programa que leia uma frase pelo teclado e mostre:
- Quantas vezes aparece a letra 'a'.
- Em que posição ela aparece pela primeira vez.
- Em que posição ela a aparece pela última vez.

In [79]:
frase = input('Digite uma frase: ').lower().strip()
print(frase.count('a'))
print(frase.find('a')+1)
print(frase.rfind('a')+1)

Digite uma frase: Arara Azul
4
1
7


21. Faça um programa que leia o nome completo de uma pessoa, mostrando em seguida o primeiro e o último separadamente.

In [85]:
nome = input('Escreva seu nome completo: ').strip().split()
print(f'Seu primeiro nome é {nome[0]}')
print(f'Seu último nome é {nome[-1]}')
#print(f'Seu último nome é {nome[len(nome)-1]}')

Escreva seu nome completo: Icaro Duarte Martins
Seu primeiro nome é Icaro
Seu último nome é Martins


22. Escreva um programa que faça o computador "pensar" em um número inteiro entre 0 e 5 e peça para o usuário tentar descobrir qual foi o número escolhido pelo computador. O programa deverá escrever na tela se o usuário venceu ou perdeu. 

Dica: Importar a função randint do módulo random (from random import randint) 

In [1]:
from random import randint # O uso de módulos será melhor explicado no caderno de módulos e pacotes.
from time import sleep

print('-=-'*20)
print('Vou pensar em um número inteiro entre 0 e 5. Tente adivinhar...')
print('-=-'*20)
x = randint(0,5) # armazena um número inteiro do intervalo [0,5]
y = int(input('Em que número eu pensei? '))

print('PROCESSANDO...')
sleep(2) # espera 2 segundos antes de executar o próximo comando
print('PARABÉNS! Você conseguiu me vencer!' if y == x else f'GANHEI! Eu pensei no {x} e não no {y}!')

-=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=-
Vou pensar em um número inteiro entre 0 e 5. Tente adivinhar...
-=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=-
Em que número eu pensei? 4
PROCESSANDO...
GANHEI! Eu pensei no 1 e não no 4!


23. Escreva um programa que leia a velocidade de um carro.
- Se ele ultrapassar 80km/h, mostre uma mensagem dizendo que ele foi multado.
- A multa vai custar R$7 por cada km/h acima do limite.

In [49]:
velocidade = float(input('Qual é velocidade atual do veículo? '))
multa = (velocidade - 80)*7

# condição simples
if velocidade > 80:
    print(f'MULTADO! Você excedeu o limite permitido que é de 80km/h')
    print(f'Você deve pagar a multa de R${multa:.2f}')
print('Tenha um bom dia! Dirija com segurança!')

Qual é velocidade atual do veículo? 100
MULTADO! Você excedeu o limite permitido que é de 80km/h
Você deve pagar a multa de R$140.00
Tenha um bom dia! Dirija com segurança!


24. Crie um programa que leia um número e mostre na tela se ele é par ou ímpar.

In [2]:
num = int(input('Me diga um número qualquer: '))

# condição composta
if num%2 == 0:
    print('Este número é par!')
else:
    print('Este número é ímpar!')

Me diga um número qualquer: 11
Este número é ímpar!


25. Desenvolva um programa que pergunte a distância de uma viagem em km.
- Calcule o preço da passagem, cobrando 0,50 por km até 200km e 0,45 para viagens mais longas.

In [5]:
distancia = float(input('Qual a distância da sua viagem? '))
print(f'Você está prestes a começar uma viagem de {distancia}km')
if distancia <= 200:
    preco = distancia*0.5
else:
    preco = distancia*0.45
print(f'E o preço da sua passagem será de R${preco:.2f}')

Qual a distância da sua viagem? 500
Você está prestes a começar uma viagem de 500.0km
E o preço da sua passagem será de R$225.00


26. Faça um programa que leia um ano qualquer e mostre se ele é bissexto.

In [78]:
from datetime import date # função importada para adicionar condição extra

ano = int(input('Que ano quer analisar? Coloque 0 para analisar o ano atual: '))

# condição simples (extra)
if ano == 0:
    ano = date.today().year # atributo da classe, isso será melhor explicado no caderno de funções

# condição composta
if ano % 4 == 0 and ano % 100 != 0 or ano % 400 == 0:
    print(f'O ano {ano} é bissexto!')
else:
    print(f'O ano {ano} não é bissexto!')

Que ano quer analisar? Coloque 0 para analisar o ano atual: 2100
O ano 2100 não é bissexto!


27. Faça um programa que leia 3 números e mostre qual é o maior e qual é o menor.

In [83]:
x = int(input('Digite o primeiro número: '))
y = int(input('Digite o segundo número: '))
z = int(input('Digite o terceiro número: '))

menor = x # define o menor como x e depois o compara
if y < x and y < z:
    menor = y
if z < x and z < y:
    menor = z

maior = x # define o maior como x e depois o compara
if y > x and y > z:
    maior = y
if z > x and z > y:
    maior = z
print(f'O maior número é {maior}')
print(f'O menor número é {menor}')

Digite o primeiro número: 12
Digite o segundo número: 90
Digite o terceiro número: 22
O maior número é 90
O menor número é 12


28. Escreva um programa que pergunte o salário de um funcionário e calcule o valor do seu aumento.
- Para salários superiores a R$1.250,00, calcule um aumento de 10%.
- Para os inferiores ou iguais, o aumento é de 15%.

In [95]:
salario = float(input('Qual é o salário do funcionário? R$'))

if salario <= 1250.00:
    salario = salario*1.15
else:
    salario = salario*1.1

print(f'Passará a ganhar R${salario:.2f}')

Qual é o salário do funcionário? R$5000
Passará a ganhar R$5500.00


29. Desenvolva um programa que leia o comprimento de 3 segmentos de reta e diga ao usuário se eles podem ou não formar um triângulo.

Dica: Para formar um triângulo, caada segmento é menor que a soma dos outros dois segmentos.

In [99]:
print('-=-'*20)
print('Analisador de Triângulos')
print('-=-'*20)
a = float(input('Primeiro segmento: '))
b = float(input('Segundo segmento: '))
c = float(input('Terceiro segmento: '))

if a < b+c and b < a+c and c < a+b:
    print('Os segmentos acima PODEM FORMAR triângulo')
else:
    print('Os segmentos acima NÃO PODEM FORMAR triângulo')

-=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=-
Analisador de Triângulos
-=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=--=-
Primeiro segmento: 3.5
Segundo segmento: 5.6
Terceiro segmento: 2.2
Os segmentos acima PODEM FORMAR triângulo


30. Escreva um programa para aprovar o empréstimo bancário para compra de uma casa. O programa vai perguntar o **valor da casa**, o **salário** do comprador e em **quantos anos** ele vai pagar.
- Calcule o valor da pestação mensal, sabendo que ele não pode exceder 30% do salário ou então o empréstimo será negado.

In [6]:
casa = float(input('Qual o valor da casa? R$'))
salario = float(input('Qual o salário do comprador? R$'))
anos = int(input('Quantos anos de financiamento? '))
prestacao = casa/(anos * 12)
minimo = salario*0.3

print(f'Pra pegar uma casa de R${casa} em {anos} anos, a prestação será de R${prestacao:.2f}')
print(f'30% do seu orçamento mensal corresponde a R${minimo:.2f}')
if prestacao <= minimo:
    print('Empréstimo pode ser CONCEDIDO!')
else:
    print('Empréstimo NEGADO!')

Qual o valor da casa? R$80000
Qual o salário do comprador? R$4000
Quantos anos de financiamento? 7
Pra pegar uma casa de R$80000.0 em 7 anos, a prestação será de R$952.38
30% do seu orçamento mensal corresponde a R$1200.00
Empréstimo pode ser CONCEDIDO!


31. Escreva um programa que leia um número inteiro qualquer e peça para usuário escolher qual será a **base de conversão**:
- 1 para Binário
- 2 para Octal
- 3 para Hexadecimal

In [34]:
num = int(input('Digite um numero inteiro qualquer: '))
opcao = int(input('''
Escolha uma das bases para conversão:
[ 1 ] Converter para BINÁRIO
[ 2 ] Converter para OCTAL
[ 3 ] Converter para HEXADECIMAL
Sua opção: '''))

if opcao == 1:
    print(f'{num} convertido para BINÁRIO é igual a {bin(num)[2:]}') #aparece 0b então fatia
elif opcao == 2:
    print(f'{num} convertido para OCTAL é igual a {oct(num)[2:]}') #aparece 0o então fatia
elif opcao == 3:
    print(f'{num} convertido para HEXADECIMAL é igual a {hex(num)[2:]}') #aparece 0x então fatia
else:
    print('Opção inválida! Tente novamente.')

Digite um numero inteiro qualquer: 834

Escolha uma das bases para conversão:
[ 1 ] Converter para BINÁRIO
[ 2 ] Converter para OCTAL
[ 3 ] Converter para HEXADECIMAL
Sua opção: 3
834 convertido para HEXADECIMAL é igual a 342


32. Escreva um programa que leia dois números inteiros e compare-os mostrando na tela uma mensagem:
- O primeiro valor é maior
- O segundo valor é maior
- Não existe valor maior, os dois são iguais.

In [22]:
a = int(input('Digite o primeiro número: '))
b = int(input('Digite o segundo número: '))

if a > b:
    print(f'O primeiro valor ({a}) é o maior!')
elif a < b:
    print(f'O segundo valor ({b}) é o maior!')
else:
    print(f'Não existe valor maior. Os dois números são iguais a {a}!')

Digite o primeiro número: 4
Digite o segundo número: 4
Não existe valor maior. Os dois números são iguais a 4!


33. Faça um programa que leia o ano de nascimento de um jovem e informe, de acordo com a sua idade:
- Se ele ainda vai se alistar no serviço militar.
- Se é a hora de se alistar.
- Se passou do tempo de alistamento.

Seu programa também deverá mostrar o tempo que falta ou que passou do prazo. </br>
Dica: Importe a função date do módulo datetime (from datetime import date)

In [42]:
from datetime import date

ano = int(input('Ano de nascimento: '))
idade = date.today().year - ano

if idade < 18:
    print(f'Quem nasceu em {ano} tem {idade} anos em {date.today().year}. \nAinda faltam {18 - idade} anos para o alistamento')
    print(f'Seu alistamento será em {ano+18}!')
elif idade == 18:
    print(f'Quem nasceu em {ano} tem {idade} anos em {date.today().year}. \nVocê tem que se alistar IMEDIATAMENTE')
else:
    print(f'Quem nasceu em {ano} tem {idade} anos em {date.today().year}. \nVocê já deveria ter se alistado há {idade-18} anos')
    print(f'Seu alistamento foi em {ano+18}')

Ano de nascimento: 2004
Quem nasceu em 2004 tem 18 anos em 2022. 
Você tem que se alistar IMEDIATAMENTE


34. Crie um programa que leia duas notas de um aluno e calcule sua média, mostrando uma mensagem no final, de acordo com a média atingida:
- Média abaixo de 5.0: Reprovado
- Média entre 5.0 e 6.9: Recuperação
- Média 7.0 ou superior: Aprovado.

In [44]:
n1 = float(input('Primeira nota: '))
n2 = float(input('Segunda nota: '))
media = (n1 + n2)/2

if media < 5.0:
    print(f'Tirando {n1} e {n2} média do aluno é {media}\nO aluno está REPROVADO!')
elif media < 7.0:
    print(f'Tirando {n1} e {n2} média do aluno é {media}\nO aluno está em RECUPERAÇÃO!')
else:
    print(f'Tirando {n1} e {n2} média do aluno é {media}\nO aluno está APROVADO!')

Primeira nota: 3
Segunda nota: 2
Tirando 3.0 e 2.0 média do aluno é 2.5
O aluno está REPROVADO!


35. A Confederação Nacional de Natação precisa de um programa que leia o ano de nascimento de um atleta e mostre sua categoria, de acordo com a idade:
- Até 9 anos: Mirim
- Até 14 anos: Infantil
- Até 19 anos: Júnior
- Até 20 anos: Sênior
- Acima: Master

Dica: Importe a função date do módulo datetime (from datetime import date)

In [46]:
from datetime import date

ano = int(input('Ano de nascimento: '))
idade = date.today().year - ano

if idade <= 9:
    print(f'O atleta tem {idade} anos. \nClassificação: MIRIM')
elif idade <= 14:
    print(f'O atleta tem {idade} anos. \nClassificação: INFANTIL')
elif idade <= 19:
    print(f'O atleta tem {idade} anos. \nClassificação: JÚNIOR')
elif idade <= 20:
    print(f'O atleta tem {idade} anos. \nClassificação: SÊNIOR')
else:
    print(f'O atleta tem {idade} anos. \nClassificação: MASTER')

Ano de nascimento: 2004
O atleta tem 19 anos. 
Classificação: JÚNIOR


36. Refaça o exercício 30 (do triângulo), acrescentando o recurso de mostrar que tipo de triângulo será formado:
- Equilátero: todos os lados iguais
- Isóceles: dois lados igiais
- Escaleno: todos os lados diferentes

In [52]:
a = float(input('Primeiro segmento: '))
b = float(input('Segundo segmento: '))
c = float(input('Terceiro segmento: '))

if a < b + c and b < a + c and c < a + b:
    print('Os segmentos PODEM FORMAR um triângulo', end = ' ')
    if a == b and a == c:
        print('EQUILÁTERO!')
    elif a != b and a != c and b != c:
        print('ESCALENO!')
    else:
        print('ISÓCELES!')
else:
    print('Os segmentos NÃO PODEM FORMAR um triângulo!')

Primeiro segmento: 3
Segundo segmento: 4
Terceiro segmento: 3
Os segmentos PODEM FORMAR um triângulo ISÓCELES!


37. Desenvolva uma lógica que leia o peso e altura de uma pessoa, calcule seu IMC e mostre seu status, de acordo com a tabela abaixo:
- Abaixo de 18.5: Abaixo do peso
- Entre 18.5 e 25: Peso ideal
- 25 até 30: Sobrepeso
- 30 até 40: Obesidade
- Acima de 40: Obesidade mórbida.

In [56]:
peso = float(input('Qual é o seu peso? (Kg) '))
altura = float(input('Qual é a sua altura? (m) '))
imc = peso/altura**2

if imc < 18.5:
    print(f'O IMC dessa pessoa é de {imc:.1f}! \nVocê está ABAIXO DO PESO normal.')
elif imc < 25:
    print(f'O IMC dessa pessoa é de {imc:.1f}! \nPARABÉNS, você está na faixa de PESO NORMAL.')
elif imc < 30:
    print(f'O IMC dessa pessoa é de {imc:.1f}! \nVocê está com sobrepeso!')
elif imc < 40:
    print(f'O IMC dessa pessoa é de {imc:.1f}! \nVocê está em OBESIDADE!')
else:
    print(f'O IMC dessa pessoa é de {imc:.1f}! \nVocê está em OBESIDADE MÓRBIDA, cuidado!')

Qual é o seu peso? (Kg) 97
Qual é a sua altura? (m) 1.96
O IMC dessa pessoa é de 25.2! 
Você está com sobrepeso!


38. Elabore um programa que Calcule o valor a ser pago por um produto, considerando seu **preço normal** e a **condição de pagamento**:
- À vista (dinheiro/cheque): 10% de desconto
- À vista no cartão: 5% de desconto
- Em até 2x no cartão: preço normal
- 3x ou mais no cartão: 20% de juros

In [66]:
print('='*5, 'LOJAS', '='*5)
preco = float(input('Preço das compras? R$'))
opcao = int(input('''
FORMAS DE PAGAMENTO
[ 1 ] à vista dinheiro/cheque
[ 2 ] à vista cartão
[ 3 ] 2x no cartão
[ 4 ] 3x ou mais no cartão
Qual é a opção? '''))

if opcao == 1:
    compra = preco*0.9
elif opcao == 2:
    compra = preco*0.95
elif opcao == 3:
    compra = preco
    parcelas = 2
    print(f'Sua compra será parcelada em {parcelas}x de {compra/parcelas:.2f} SEM JUROS')
elif opcao == 4:
    compra = preco*1.2
    parcelas = int(input('Quantas parcelas? '))
    print(f'Sua compra será parcelada em {parcelas}x de {compra/parcelas:.2f} COM JUROS')
print(f'Sua compra de {preco:.2f} vai custar {compra:.2f} no final')

===== LOJAS =====
Preço das compras? R$500

FORMAS DE PAGAMENTO
[ 1 ] à vista dinheiro/cheque
[ 2 ] à vista cartão
[ 3 ] 2x no cartão
[ 4 ] 3x ou mais no cartão
Qual é a opção? 4
Quantas parcelas? 7
Sua compra será parcelada em 7x de 85.71 COM JUROS
Sua compra de 500.00 vai custar 600.00 no final


39. Crie um programa que faça o computador jogar jokenpô com você.

Dica: Importe a função randint do módulo random (from random import randint)

In [7]:
from random import randint
from time import sleep

itens = ('Pedra', 'Papel', 'Tesoura') # tupla
computador = randint(0,2)
jogador = int(input('''
Suas opções:
[ 1 ] PEDRA
[ 2 ] PAPEL
[ 3 ] TESOURA
Qual é a sua jogada?''')) - 1 # é necessário subtrair 1, pois o índice começa em 0

print('JO')
sleep(1)
print('KEN')
sleep(1)
print('PO!!!')
print('-='*12)
print(f'Computador jogou {itens[computador]} \nJogador jogou {itens[jogador]}!')
print('-='*12)

if computador == 0:
    if jogador == 0:
        print('EMPATE')
    elif jogador == 1:
        print('JOGADOR VENCE')
    elif jogador ==2:
        print('COMPUTADOR VENCE')
    else:
        print('JOGADA INVÁLIDA!')
elif computador == 1:
    if jogador == 0:
        print('COMPUTADOR VENCE')
    elif jogador == 1:
        print('EMPATE')
    elif jogador ==2:
        print('JOGADOR VENCE')
    else:
        print('JOGADA INVÁLIDA!')
elif computador ==2:
    if jogador == 0:
        print('JOGADOR VENCE')
    elif jogador == 1:
        print('COMPUTADOR VENCE')
    elif jogador ==2:
        print('EMPATE')
    else:
        print('JOGADA INVÁLIDA!')        


Suas opções:
[ 1 ] PEDRA
[ 2 ] PAPEL
[ 3 ] TESOURA
Qual é a sua jogada?3
JO
KEN
PO!!!
-=-=-=-=-=-=-=-=-=-=-=-=
Computador jogou Tesoura 
Jogador jogou Tesoura!
-=-=-=-=-=-=-=-=-=-=-=-=
EMPATE


40. Faça um programa que mostre na tela uma contagem regressiva para estouro de fogos de artifício, indo de 10 até 0, com pausa de 1 segundo entre eles.

Dica: Importe a função sleep do módulo time (from time import sleep)

In [33]:
from time import sleep
from emoji import emojize # necessário instalar

for c in range(10,-1,-1):
    print(c)
    sleep(1)
print(emojize('BUM! BUM! POOOW! :fireworks:'))

10
9
8
7
6
5
4
3
2
1
0
BUM! BUM! POOOW! 🎆


41. Crie um programa que mostre na tela todos os números pares entre 1 e 50.

In [37]:
for c in range(2, 51, 2): # começa de 0 e soma 2, portanto: pares
    print(c, end=' ')
print('Acabou')

2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 Acabou


42. Faça um programa que calcule a soma entre todos os números ímpares que são múltiplos de três e que se encontram no intervalo de 1 até 500.

In [41]:
soma = 0 # acumulador
cont = 0 # contador

for c in range(1, 501, 2): # começa de 1 e soma 2, portanto: ímpares
    if c % 3 == 0:
        soma += c #s = s + c
        cont += 1
print(f'A soma de todos os {cont} valores solicitados é {soma}')

A soma de todos os 83 valores solicitados é 20667


43. Refaça o exercício 9, mostrando a tabuada de um número que o usuário escolhe, só que agora utilizando o laço for.

In [1]:
n = int(input('Digite um número para ver sua tabuada: '))

for c in range(1, 11):
    print(f'{n} x {c} = {n*c}')

Digite um número para ver sua tabuada: 7
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70


44. Desenvolva um programa que leia 6 números inteiros e mostre a soma apenas daqueles que forem pares. Se o valor digitado for ímpar, desconsidere-o.

In [2]:
soma = 0
cont = 0

for c in range(1, 7):
    num = int(input(f'Digite o {c}º número: '))
    if num % 2 == 0:
        soma += num
        cont += 1
print(f'A soma dos {cont} números pares é {soma}')

Digite o 1º número: 2
Digite o 2º número: 3
Digite o 3º número: 4
Digite o 4º número: 5
Digite o 5º número: 6
Digite o 6º número: 7
A soma dos 3 números pares é 12


45. Desenvolva um programa que leia o **primeiro termo** e a **razão** de uma PA. No final mostre os 10 primeiros termos da progressão.

In [56]:
print('='*30)
print(f'{"10 TERMOS DE UMA PA":^30}')
print('='*30)
a1 = int(input('Primeiro termo: '))
r = int(input('Razão: '))
a10 = a1 + (10 - 1) * r #fórmula de an

for c in range(a1, a10 + r, r): # [a1, a10 + r)
    print(c, end=' ➝ ')
print('Acabou')

     10 TERMOS DE UMA PA      
Primeiro termo: 5
Razão: 5
5 ➝ 10 ➝ 15 ➝ 20 ➝ 25 ➝ 30 ➝ 35 ➝ 40 ➝ 45 ➝ 50 ➝ Acabou


46. Faça um programa que leia um número inteiro e diga se ele é ou não um número primo.

In [67]:
n = int(input('Digite um número: '))
cont = 0

for c in range(1, n+1):
    if n % c ==0:
        print('\033[34m', end=' ') #azul
        cont += 1
    else:
        print('\033[31m', end=' ') #vermelho
    print(c, end=' ')
print(f'\n\033[mO número {n} foi divisível {cont} vezes!')

if cont == 2:
    print(f'O número {n} é PRIMO!')
else:
    print(f'O número {n} NÃO É PRIMO!')

Digite um número: 14
 1  2  3  4  5  6  7  8  9  10  11  12  13  14 
O número 14 foi divisível 4 vezes!
O número 14 NÃO É PRIMO!


47. Crie um programa que leia uma frase qualquer e diga se ela é um palíndromo, desconsiderando os espaços e acentos.

Exemplo: Apos a sopa (leia de trás pra frente)

In [3]:
frase = str(input('Digite uma frase: ')).upper().strip().replace(' ', '')
inverso = ''

'''
for letra in range(len(frase) -1, -1, -1):
    inverso += frase[letra]
'''

inverso = frase[::-1] # fatiamento de string (particularidade do python)

print(f'O inverso de {frase} é {inverso}')
if inverso == frase:
    print('Temos um palíndromo!')
else:
    print('A frase digitada não é um palíndromo!')

Digite uma frase: Anotaram a data da maratona
O inverso de ANOTARAMADATADAMARATONA é ANOTARAMADATADAMARATONA
Temos um palíndromo!


48. Crie um programa que leia o ano de nascimento de sete pessoas. No final, mostre quantas pessoas ainda não atingiram a maioridade e quantas já são maiores.

Dica: Importe a função date do módulo datetime (from datetime import date)

In [85]:
from datetime import date

maior, menor = 0, 0

for c in range(1, 8):
    nasc = int(input(f'Em que ano a {c}ª pessoa nasceu? '))
    idade = date.today().year - nasc
    if idade >= 21:
        maior +=1
    else:
        menor +=1
print(f'Ao todo tivemos {maior} pessoas maiores de idade \nE também tivemos {menor} pessoas menores de idade')

Em que ano a 1ª pessoa nasceu? 2010
Em que ano a 2ª pessoa nasceu? 1960
Em que ano a 3ª pessoa nasceu? 2011
Em que ano a 4ª pessoa nasceu? 1970
Em que ano a 5ª pessoa nasceu? 2015
Em que ano a 6ª pessoa nasceu? 1940
Em que ano a 7ª pessoa nasceu? 2016
Ao todo tivemos 3 pessoas maiores de idade 
E também tivemos 4 pessoas menores de idade


49. Faça um programa que leia o peso de 5 pessoas. No final, mostre qual foi o maior e o menor peso lidos.

In [5]:
for c in range(1, 6):
    peso = float(input(f'Peso(kg) da {c}ª pessoa: '))
    if c == 1:
        maior = peso
        menor = peso
    else:
        if peso > maior:
            maior = peso
        elif peso < menor:
            menor = peso
print(f'O maior peso lido foi de {maior}kg \nE o menor peso lido foi de {menor}kg')

Peso(kg) da 1ª pessoa: 32.5
Peso(kg) da 2ª pessoa: 69.3
Peso(kg) da 3ª pessoa: 54.8
Peso(kg) da 4ª pessoa: 86.5
Peso(kg) da 5ª pessoa: 42.5
O maior peso lido foi de 86.5kg 
E o menor peso lido foi de 32.5kg


50. Desenvolva um programa que leia nome, idade e sexo de 4 pessoas. No final do programa, mostre:
- A média de idade do grupo
- Qual é o nome do homem mais velho
- Quantas mulheres têm menos de 20 anos.

In [11]:
soma_idade = 0
maior_idade_homem = 0
nome_velho = ''
count_mulher_20 = 0

for c in range(1, 5):
    print('-'*5, f'{c}ª pessoa','-'*5)
    nome = str(input('Nome: ')).strip()
    idade = int(input('Idade: '))
    sexo = str(input('Sexo [M/F]: ')).strip()
    soma_idade += idade
    if sexo in 'Mm' and idade > maior_idade_homem:
        maior_idade_homem = idade
        nome_velho = nome
    if sexo in 'Ff' and idade < 20:
        count_mulher_20 += 1

media = soma_idade/c

print(f'A média de idade do grupo é de {media:.1f} anos')
print(f'O homem mais velho tem {maior_idade_homem} anos e se chama {nome_velho}')
print(f'Ao todo são {count_mulher_20} mulheres com menos de 20 anos')

----- 1ª pessoa -----
Nome: Jéssica
Idade: 23
Sexo [M/F]: F
----- 2ª pessoa -----
Nome: Cláudio
Idade: 12
Sexo [M/F]: M
----- 3ª pessoa -----
Nome: Pedro
Idade: 75
Sexo [M/F]: M
----- 4ª pessoa -----
Nome: Maria
Idade: 15
Sexo [M/F]: F
A média de idade do grupo é de 31.2 anos
O homem mais velho tem 75 anos e se chama Pedro
Ao todo são 1 mulheres com menos de 20 anos


51. Faça um programa que leia sexo de uma pessoa, mas só aceite os valores M ou F. Caso esteja errado, peça a digitação novamente até ter um valor correto.

In [5]:
sexo = str(input('Informe seu sexo [M/F]: ')).strip().upper()[0]

while sexo not in 'MmFf': # validação
    sexo = str(input('Dados inválidos. Por favor, informe seu sexo [M/F]: ')).strip().upper()[0]
print(f'Sexo {sexo} registrado com sucesso')

Informe seu sexo [M/F]: n
Dados inválidos. Por favor, informe seu sexo [M/F]:    l
Dados inválidos. Por favor, informe seu sexo [M/F]: k   
Dados inválidos. Por favor, informe seu sexo [M/F]:   Feminino
Sexo F registrado com sucesso


52. Melhore o jogo do exercício 22, onde o computador vai "pensar" em um número entre 0 e 10. Só que agora o jogador vai tentar advinhar até acertar, mostrando no final quantos palpites foram necessários para vencer.

In [14]:
from random import randint

computador = randint(0, 10)
print('''Sou seu computador...
Acabei de pensar em um número entre 0 e 10.
Será que você consegue advinhar qual foi?''')
acertou = False
palpites = 0

while not acertou: # validação
    jogador = int(input('Qual é o seu palpite? '))
    palpites += 1
    if jogador == computador:
        acertou = True
    else:
        if jogador < computador:
            print('Mais... tente mais uma vez.')
        else:
            print('Menos... tente mais uma vez.')
print(f'Acertou com {palpites} tentativas. Parabéns!')

Sou seu computador...
Acabei de pensar em um número entre 0 e 10.
Será que você consegue advinhar qual foi?
Qual é o seu palpite? 2
Mais... tente mais uma vez.
Qual é o seu palpite? 9
Menos... tente mais uma vez.
Qual é o seu palpite? 5
Menos... tente mais uma vez.
Qual é o seu palpite? 4
Acertou com 4 tentativas. Parabéns!


53. Crie um programa que leia 2 valores e mostre um menu na tela:
- [1] Somar
- [2] multiplicar
- [3] maior
- [4] novos números
- [5] sair

Seu programa deverá realizar a operação solicitada em cada caso.

In [22]:
from time import sleep

n1 = int(input('Primeiro valor: '))
n2 = int(input('Segundo valor: '))
opcao = 0

while opcao != 5:
    print('''O que deseja fazer?
    [ 1 ] Somar
    [ 2 ] Multiplicar
    [ 3 ] Maior
    [ 4 ] Novos números
    [ 5 ] Sair''')
    opcao = int(input('>>> Qual é a sua opção? '))
    if opcao == 1:
        soma = n1 + n2
        print(f'A soma de {n1} + {n2} é {soma}')
    elif opcao == 2:
        produto = n1 * n2
        print(f'O produto entre {n1} x {n2} é {produto}')
    elif opcao == 3:
        if n1 > n2:
            maior = n1
        else:
            maior = n2
        print(f'O maior valor entre {n1} e {n2} é {maior}')
    elif opcao == 4:
        print('Informe os números novamente:')
        n1 = int(input('Primeiro valor: '))
        n2 = int(input('Segundo valor: '))
    elif menu == 5:
        print('Saindo...')
    else:
        print('Opção inválida. Tente novamente.')
    print('=-='*10)
    sleep(2)
print('Fim do programa. Volte sempre.')

Primeiro valor: 6
Segundo valor: 0
O que deseja fazer?
    [ 1 ] Somar
    [ 2 ] Multiplicar
    [ 3 ] Maior
    [ 4 ] Novos números
    [ 5 ] Sair
>>> Qual é a sua opção? 1
A soma de 6 + 0 é 6
=-==-==-==-==-==-==-==-==-==-=
O que deseja fazer?
    [ 1 ] Somar
    [ 2 ] Multiplicar
    [ 3 ] Maior
    [ 4 ] Novos números
    [ 5 ] Sair
>>> Qual é a sua opção? 2
O produto entre 6 x 0 é 0
=-==-==-==-==-==-==-==-==-==-=
O que deseja fazer?
    [ 1 ] Somar
    [ 2 ] Multiplicar
    [ 3 ] Maior
    [ 4 ] Novos números
    [ 5 ] Sair
>>> Qual é a sua opção? 3
O maior valor entre 6 e 0 é 6
=-==-==-==-==-==-==-==-==-==-=
O que deseja fazer?
    [ 1 ] Somar
    [ 2 ] Multiplicar
    [ 3 ] Maior
    [ 4 ] Novos números
    [ 5 ] Sair
>>> Qual é a sua opção? 4
Informe os números novamente:
Primeiro valor: 3
Segundo valor: 5
=-==-==-==-==-==-==-==-==-==-=
O que deseja fazer?
    [ 1 ] Somar
    [ 2 ] Multiplicar
    [ 3 ] Maior
    [ 4 ] Novos números
    [ 5 ] Sair
>>> Qual é a sua opção? 5
Saind

54. Faça um programa que leia um número qualquer e mostre seu fatorial.

In [26]:
# usando módulo math

from math import factorial

num = int(input('Digite um número para \ncalcular seu fatorial: '))
fat = factorial(num)

print(f'O fatorial de {num} é {fat}')

Digite um número para 
calcular seu fatorial: 5
O fatorial de 5 é 120


In [1]:
from time import sleep

num = c = int(input('Digite um número para calcular seu fatorial: '))
fat = 1

print(f'Calculando {num}! = ', end='')
sleep(2)
while c > 0:
    print(c, end=' ')
    print('x ' if c > 1 else 'x 0! = ', end='')
    fat *= c
    c -= 1
print(fat)

Digite um número para calcular seu fatorial: 5
Calculando 5! = 5 x 4 x 3 x 2 x 1 x 0! = 120


55. Refaça o exercício 45, lendo o **primeiro termo** e a **razão** de uma PA, mostrando os 10 primeiros termos da progressão usando a estrutura while.

In [53]:
print('='*30)
print(f'{"10 TERMOS DE UMA PA":^30}')
print('='*30)
a1 = int(input('Primeiro termo: '))
r = int(input('Razão: '))
termo = a1 # inicializando
cont = 1 # contador

while cont <= 10:
    print(termo, end=' ➝ ')
    termo += r
    cont +=1
print('Acabou')

     10 TERMOS DE UMA PA      
Primeiro termo: 2
Razão: 4
2 ➝ 6 ➝ 10 ➝ 14 ➝ 18 ➝ 22 ➝ 26 ➝ 30 ➝ 34 ➝ 38 ➝ Acabou


56. Melhore o exercício 55, perguntando para o usuário se ele quer mostrar mais alguns termos. O programa encerra quando ele disser que quer mostrar 0 termos.

In [60]:
print('='*30)
print(f'{"GERADOR DE PA":^30}')
print('='*30)
a1 = int(input('Primeiro termo: '))
r = int(input('Razão: '))
termo = a1 # inicializando
cont = 1 # contador
mais = 10 # continua mostrando os 10 primeiros termos
total = 0

while mais != 0:
    total += mais
    while cont <= total:
        print(termo, end=' ➝ ')
        termo += r
        cont +=1
    print('PAUSA')
    mais = int(input('Quantos termos você quer mostrar a mais? '))
print(f'A progressão foi finalizada com {total} termos mostrados.')

        GERADOR DE PA         
Primeiro termo: 0
Razão: 5
0 ➝ 5 ➝ 10 ➝ 15 ➝ 20 ➝ 25 ➝ 30 ➝ 35 ➝ 40 ➝ 45 ➝ PAUSA
Quantos termos você quer mostrar a mais? 5
50 ➝ 55 ➝ 60 ➝ 65 ➝ 70 ➝ PAUSA
Quantos termos você quer mostrar a mais? 10
75 ➝ 80 ➝ 85 ➝ 90 ➝ 95 ➝ 100 ➝ 105 ➝ 110 ➝ 115 ➝ 120 ➝ PAUSA
Quantos termos você quer mostrar a mais? 2
125 ➝ 130 ➝ PAUSA
Quantos termos você quer mostrar a mais? 0
A progressão foi finalizada com 27 termos mostrados.


57. Escreva um programa que leia um número inteiro n qualquer e mostre na tela os n primeiros elementos de uma sequência de fibonacci.

In [1]:
print('-'*30)
print('Sequência de Fibonacci')
print('-'*30)
n = int(input('Quantos termos deseja mostrar? '))

a1 = 0
a2 = 1
fibo = a1 # inicializando
cont = 1 # contador
print('~'*30)

while cont <= n:
    print(fibo, end=' ➝ ')
    a1 = a2
    a2 = fibo
    fibo = a1 + a2
    cont += 1
print('FIM')
print('~'*30)

------------------------------
Sequência de Fibonacci
------------------------------
Quantos termos deseja mostrar? 8
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0 ➝ 1 ➝ 1 ➝ 2 ➝ 3 ➝ 5 ➝ 8 ➝ 13 ➝ FIM
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


58. Crie um programa que leia vários números inteiros pelo teclado. O programa só vai parar quando o usuário digitar 999, que é a condição de parada. No final, mostre quantos números foram digitados e qual foi a soma entre eles (desconsiderando o flag).

In [22]:
soma = cont = 0
num = int(input('Digite um número [999 para parar]: '))

while num != 999:
    soma += num
    cont +=1
    num = int(input('Digite um número [999 para parar]: '))
print(f'Você digitou {cont} números e a soma entre eles foi {soma}')

Digite um número [999 para parar]: 8
Digite um número [999 para parar]: 2
Digite um número [999 para parar]: 1
Digite um número [999 para parar]: 7
Digite um número [999 para parar]: 999
Você digitou 4 números e a soma entre eles foi 18


59. Crie um programa que leia vários números inteiros pelo teclado. No final da execução, mostre a média entre todos os valores e quais foram o maior e menor valores lidos. O programa deve perguntar ao usuário se ele quer ou não continuar a digitar os valores.

In [27]:
soma = cont = 0
resp = 'S'

while resp in 'Ss':
    num = int(input('Digite um número: '))
    soma += num
    cont += 1
    if cont == 1:
        maior = menor = num
    else:
        if num > maior:
            maior = num
        if num < menor:
            menor = num
    resp = str(input('Deseja continuar? [S/N]')).upper().strip()[0]

media = soma/cont # calcular media no final para não ficar calculando na repetição

print(f'Você digitou {cont} números e a média foi de {media:.2f}')
print(f'O maior valor foi {maior} e o menor foi {menor}')

Digite um número: 4
Deseja continuar? [S/N]s
Digite um número: 2
Deseja continuar? [S/N]s
Digite um número: 8
Deseja continuar? [S/N]s
Digite um número: 9
Deseja continuar? [S/N]n
Você digitou 4 números e a média foi de 5.75
O maior valor foi 9 e o menor foi 2


60. Crie um programa que leia vários números inteiros pelo teclado. O programa só vai parar quando o usuário digitar o valor 999, que é a condição de parada. No final, mostre quantos números foram digitados e qual foi a soma entre eles (desconsiderando o flag).

In [2]:
cont = soma = 0

while True:
    num = int(input('Digite um valor [999 para parar]: '))
    if num == 999: # flag
        break
    cont += 1 # vem depois, pois assim não conta o flag
    soma += num # vem depois, pois assim não soma o flag
print(f'A soma dos {cont} valores foi {soma}')

Digite um valor [999 para parar]: 3
Digite um valor [999 para parar]: 8
Digite um valor [999 para parar]: 1
Digite um valor [999 para parar]: 7
Digite um valor [999 para parar]: 999
A soma dos 4 valores foi 19


61. Faça um programa que mostre a tabuada de vários números, um de cada vez, para cada valor digitado pelo usuário. O programa será interrompido quando o número solicitado for negativo.

In [11]:
while True:
    num = int(input('Quer ver a tabuada de qual valor? '))
    print('-'*20)
    if num < 0: #flag
        break
    for c in range(1, 11):
        print(f'{num} x {c} = {num*c}')
    print('-'*20)
print('PROGRAMA DE TABUADA ENCERRADO. Volte sempre!')

Quer ver a tabuada de qual valor? 6
--------------------
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60
--------------------
Quer ver a tabuada de qual valor? 9
--------------------
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90
--------------------
Quer ver a tabuada de qual valor? -9
--------------------
PROGRAMA DE TABUADA ENCERRADO. Volte sempre!


62. Faça um programa que jogue par ou ímpar com o computador. O jogo será interrompido quando o jogador perder, mostrando o total de vitórias consecutivas que ele conquistou no final do jogo.

In [3]:
from random import randint

print('=-'*20)
print('VAMOS JOGAR PAR OU ÍMPAR')
print('=-'*20)
vitorias = 0

while True:
    jogador = int(input('Diga um valor: '))
    computador = randint(0, 10)
    soma = jogador + computador
    escolha = ' ' # esvaziar escolha quando reiniciar
    while escolha not in 'PI':
        escolha = str(input('Par ou Ímpar? [P/I] ')).upper().strip()[0]
    print(f'Você jogou {jogador} e o computador {computador}. A soma é {soma}. ', end ='')
    print('DEU PAR' if soma % 2 == 0 else 'DEU ÍMPAR')
    if escolha == 'P':
        if soma % 2 == 0:
            print('Você VENCEU!')
            vitorias += 1
        else:
            print('Você PERDEU!')
            break
    elif escolha == 'I':
        if soma % 2 == 1:
            print('Você VENCEU!')
            vitorias += 1
        else:
            print('Você PERDEU!')
            break
    print('Vamos jogar novamente...')
print(f'GAME OVER! Você venceu {vitorias} vezes')

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
VAMOS JOGAR PAR OU ÍMPAR
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Diga um valor: 10
Par ou Ímpar? [P/I] par
Você jogou 10 e o computador 10. A soma é 20. DEU PAR
Você VENCEU!
Vamos jogar novamente...
Diga um valor: 9
Par ou Ímpar? [P/I] par
Você jogou 9 e o computador 6. A soma é 15. DEU ÍMPAR
Você PERDEU!
GAME OVER! Você venceu 1 vezes


63. Crie um programa que leia a idade e o sexo de várias pessoas. A cada pessoa cadastrada, o programa deverá perguntar se o usuário quer ou não continuar. No final, mostre:
- Quantas pessoas tem mais de 18 anos.
- Quantos homens foram cadastrados.
- Quantas mulheres tem menos de 20 anos.

In [23]:
tot18 = toth = totm20 = 0

while True:
    print('-'*30)
    print(f'{"CADASTRE UMA PESSOA":^30}')
    print('-'*30)
    idade = int(input('Idade: '))
    sexo = ' ' # limpa a variável quando reiniciar o loop
    while sexo not in 'MF':
        sexo = str(input('Sexo: [M/F] ')).strip().upper()[0]
    print('-'*30)
    if idade >= 18:
        tot18 += 1
    if sexo == 'M':
        toth += 1
    if sexo == 'F' and idade < 20:
        totm20 += 1
    resp = ' ' # limpa a variável quando reiniciar o loop
    while resp not in 'SN':
        resp = str(input('Quer continuar? [S/N] ')).strip().upper()[0]
    if resp == 'N':
        break # não reinicia o loop

print(f'O total de pessoas com mais de 18 anos é {tot18}.')
print(f'Ao todo temos {toth} homens cadastrados.')
print(f'E temos {totm20} mulheres com menos de 20 anos.')

------------------------------
     CADASTRE UMA PESSOA      
------------------------------
Idade: 22
Sexo: [M/F] m
------------------------------
Quer continuar? [S/N] s
------------------------------
     CADASTRE UMA PESSOA      
------------------------------
Idade: 16
Sexo: [M/F] f
------------------------------
Quer continuar? [S/N] s
------------------------------
     CADASTRE UMA PESSOA      
------------------------------
Idade: 45
Sexo: [M/F] f
------------------------------
Quer continuar? [S/N] s
------------------------------
     CADASTRE UMA PESSOA      
------------------------------
Idade: 12
Sexo: [M/F] m
------------------------------
Quer continuar? [S/N] n
O total de pessoas com mais de 18 anos é 2.
Ao todo temos 2 homens cadastrados.
E temos 1 mulheres com menos de 20 anos.


64. Crie um programa que leia o nome e o preço de vários produtos. O programa deverá perguntar se o usuário vai continuar. No final, mostre:
- Qual é o total gasto na compra.
- Quantos produtos custam mais de 1000.
- Qual é o nome do produto mais barato.

In [31]:
total = totmil = cont = 0

print('-'*30)
print(f'{"LOJA SUPER BARATÃO":^30}')
print('-'*30)

while True:
    produto = str(input('Nome do Produto: ')).strip()
    preco = float(input('Preço: R$'))
    cont += 1 # necessário para saber se é o primeiro
    total += preco
    if preco > 1000:
        totmil += 1
    if cont == 1 or preco < menor: #usa o or para simplificar e não ter 2 blocos iguais
        menor = preco
        barato = produto
    resp = ' '
    while resp not in 'SN':
        resp = str(input('Quer continuar? [S/N]')).upper().strip()[0]
    if resp == 'N':
        break

print(f'{" FIM DO PROGRAMA ":-^40}')
print(f'O total da compra foi R${total:.2f}')
print(f'Temos {totmil} produtos custando mais de R$1000')
print(f'O produto mais barato foi {barato} que custa R${menor:.2f}')

------------------------------
      LOJA SUPER BARATÃO      
------------------------------
Nome do Produto: Lapiseira
Preço: R$6
Quer continuar? [S/N]s
Nome do Produto: Caderno
Preço: R$25
Quer continuar? [S/N]s
Nome do Produto: Computador
Preço: R$12000
Quer continuar? [S/N]s
Nome do Produto: Impressora
Preço: R$750
Quer continuar? [S/N]n
----------- FIM DO PROGRAMA ------------
O total da compra foi R$12781.00
Temos 1 produtos custando mais de R$1000
O produto mais barato foi Lapiseira que custa R$6.00


65. Crie um programa que simule o funcionamento de um caixa eletrônico. No início, pergunte ao usuário qual será o valor a ser sacado (número inteiro) e o programa vai informar quantas cédulas de cada valor serão entregues. 

Obs.: Considere que o caixa possui cédulas de RS50, RS20, RS10 e RS1.

In [10]:
print('='*30)
print(f'{"BANCO CEV":^30}')
print('='*30)
valor = int(input('Que valor você quer sacar? R$'))
total = valor
cedula = 50
total_cedula = 0

while True:
    if total >= cedula: 
        total -= cedula 
        total_cedula += 1 
    else:
        if total_cedula > 0:
            print(f'Total de {total_cedula} cédulas de R${cedula}')
        if cedula == 50:
            cedula = 20
        elif cedula == 20:
            cedula = 10
        elif cedula == 10:
            cedula = 1
        total_cedula = 0
        if total == 0:
            break

print('='*30)
print('Volte sempre ao BANCO CEV! Tenha um bom dia!')    

          BANCO CEV           
Que valor você quer sacar? R$134
Total de 2 cédulas de R$50
Total de 1 cédulas de R$20
Total de 1 cédulas de R$10
Total de 4 cédulas de R$1
Volte sempre ao BANCO CEV! Tenha um bom dia!


In [9]:
print('='*30)
print(f'{"BANCO CEV":^30}')
print('='*30)
valor = int(input('Que valor você quer sacar? R$'))
cedula = 50

while True:
    if valor >= cedula:
        total_cedula = valor // cedula
        valor %= cedula
        print(f'Total de {total_cedula} cédulas de R${cedula}')
        if valor == 0:
            break
    else:
        if cedula == 50:
            cedula = 20
        elif cedula == 20:
            cedula = 10
        elif cedula == 10:
            cedula = 1

print('='*30)
print('Volte sempre ao BANCO CEV! Tenha um bom dia!')

          BANCO CEV           
Que valor você quer sacar? R$134
Total de 2 cédulas de R$50
Total de 1 cédulas de R$20
Total de 1 cédulas de R$10
Total de 4 cédulas de R$1
Volte sempre ao BANCO CEV! Tenha um bom dia!


In [13]:
# utilizando for e lista

print('='*30)
print(f'{"BANCO CEV":^30}')
print('='*30)
valor = int(input('Que valor você quer sacar? R$'))

for cedula in [50, 20, 10, 1]: # percorrendo lista
    if valor >= cedula:
        total_cedula = valor // cedula
        valor %= cedula
        print(f'Total de {total_cedula} cédulas de R${cedula}')
        if valor == 0:
            break

print('='*30)
print('Volte sempre ao BANCO CEV! Tenha um bom dia!')

          BANCO CEV           
Que valor você quer sacar? R$134
Total de 2 cédulas de R$50
Total de 1 cédulas de R$20
Total de 1 cédulas de R$10
Total de 4 cédulas de R$1
Volte sempre ao BANCO CEV! Tenha um bom dia!


66. Crie uma tupla totalmente preenchida com um contagem por extenso, de zero até vinte. Seu programa deverá ler um número pelo teclado (entre 0 e 20) e mostrá-lo por extenso.

In [63]:
cont = ('zero', 'um', 'dois', 'três', 'quatro', 'cinco',
        'seis', 'sete', 'oito', 'nove', 'dez',
        'onze', 'doze', 'treze', 'catorze', 'quinze',
        'dezesseis', 'dezessete', 'dezoito', 'dezenove', 'vinte')

while True:
    num = int(input('Digite um número entre 0 e 20: '))
    if 0 <= num <= 20:
        break
    print('Tente novamente. ', end='')

print(f'Você digitou o número {cont[num]}')

Digite um número entre 0 e 20: 90
Tente novamente. Digite um número entre 0 e 20: 13
Você digitou o número treze


In [77]:
cont = ('zero', 'um', 'dois', 'três', 'quatro', 'cinco',
        'seis', 'sete', 'oito', 'nove', 'dez',
        'onze', 'doze', 'treze', 'catorze', 'quinze',
        'dezesseis', 'dezessete', 'dezoito', 'dezenove', 'vinte')

while True:
    while True:
        num = int(input('Digite um número entre 0 e 20: '))
        if 0 <= num < len(cont):
            break
        print('Tente novamente. ', end='')
    print(f'Você digitou o número {cont[num]}')
    resp = str(input('Quer continuar? [S/N] ')).strip().upper()[0]
    if resp == 'N':
        break

Digite um número entre 0 e 20: 21
Tente novamente. Digite um número entre 0 e 20: 19
Você digitou o número dezenove
Quer continuar? [S/N] n


67. Crie uma tupla preenchida com os 20 primeiros colocados no campeonato brasileiro de futebol, na ordem de colocação. Depois mostre:
- Apenas os 5 primeiros colocados
- Os últimos 4 colocados da tabela
- Uma lista com os times em ordem alfabética
- Em que posição na tabela está o time do São Paulo

In [81]:
times = ('Palmeiras', 'Internacional', 'Fluminense', 'Corinthians', 'Flamengo',
         'Athletico-PR', 'Atlético-MG', 'Fortaleza', 'São Paulo', 'América-MG',
         'Botafogo', 'Santos', 'Goiás', 'Bragantino', 'Coritiba',
         'Cuiabá', 'Ceará', 'Atlético-GO', 'Avaí', 'Juventude')

print('-='*20)
print(f'Lista de times do Brasileirão: {times}')

print('-='*20)
print(f'Os 5 primeiros são: {times[:5]}') # [0,5)

print('-='*20)
print(f'Os 4 últimos são: {times[-4:]}') # [-4,-1]

print('-='*20)
print(f'Times em ordem alfabética: {sorted(times)}')

print('-='*20)
print(f'O São Paulo está na {times.index("São Paulo")+1}ª posição')

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Lista de times do Brasileirão: ('Palmeiras', 'Internacional', 'Fluminense', 'Corinthians', 'Flamengo', 'Athletico-PR', 'Atlético-MG', 'Fortaleza', 'São Paulo', 'América-MG', 'Botafogo', 'Santos', 'Goiás', 'Bragantino', 'Coritiba', 'Cuiabá', 'Ceará', 'Atlético-GO', 'Avaí', 'Juventude')
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Os 5 primeiros são: ('Palmeiras', 'Internacional', 'Fluminense', 'Corinthians', 'Flamengo')
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Os 4 últimos são: ('Ceará', 'Atlético-GO', 'Avaí', 'Juventude')
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Times em ordem alfabética: ['América-MG', 'Athletico-PR', 'Atlético-GO', 'Atlético-MG', 'Avaí', 'Botafogo', 'Bragantino', 'Ceará', 'Corinthians', 'Coritiba', 'Cuiabá', 'Flamengo', 'Fluminense', 'Fortaleza', 'Goiás', 'Internacional', 'Juventude', 'Palmeiras', 'Santos', 'São Paulo']
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
O São Paulo está na 9ª posição


In [78]:
times = ('Palmeiras', 'Internacional', 'Fluminense', 'Corinthians', 'Flamengo',
         'Athletico-PR', 'Atlético-MG', 'Fortaleza', 'São Paulo', 'América-MG',
         'Botafogo', 'Santos', 'Goiás', 'Bragantino', 'Coritiba',
         'Cuiabá', 'Ceará', 'Atlético-GO', 'Avaí', 'Juventude')

print('-='*20)
print('Lista de times do Brasileirão: ', end='')
for pos, time in enumerate(times):
    print(pos+1, time, end=' ')

print('\n', '-='*20)
print('Os 5 primeiros são: ', end='')
for pos, time in enumerate(times[0:5]):
    print(pos+1, time, end =' ')

print('\n', '-='*20)
print('Os 4 últimos são: ', end='')
for pos in range(16, len(times)):
    print(pos+1, times[pos], end=' ')

print('\n', '-='*20)
print('Times em ordem alfabética:', sorted(times))

print('-='*20)
print(f'O São Paulo está na {times.index("São Paulo")+1}ª posição')

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Lista de times do Brasileirão: 1 Palmeiras 2 Internacional 3 Fluminense 4 Corinthians 5 Flamengo 6 Athletico-PR 7 Atlético-MG 8 Fortaleza 9 São Paulo 10 América-MG 11 Botafogo 12 Santos 13 Goiás 14 Bragantino 15 Coritiba 16 Cuiabá 17 Ceará 18 Atlético-GO 19 Avaí 20 Juventude 
 -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Os 5 primeiros são: 1 Palmeiras 2 Internacional 3 Fluminense 4 Corinthians 5 Flamengo 
 -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Os 4 últimos são: 17 Ceará 18 Atlético-GO 19 Avaí 20 Juventude 
 -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Times em ordem alfabética: ['América-MG', 'Athletico-PR', 'Atlético-GO', 'Atlético-MG', 'Avaí', 'Botafogo', 'Bragantino', 'Ceará', 'Corinthians', 'Coritiba', 'Cuiabá', 'Flamengo', 'Fluminense', 'Fortaleza', 'Goiás', 'Internacional', 'Juventude', 'Palmeiras', 'Santos', 'São Paulo']
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
O São Paulo está na 9ª posição


68. Crie um programa que vai gerar 5 números aleatórios e colocar em uma tupla. Depois disso, mostre a listagem de números gerados e também indique o menor e o maior valor que estão na tupla.

In [7]:
from random import randint

tupla = (randint(1, 10), randint(1, 10), randint(1, 10),
         randint(1, 10), randint(1, 10))

print('Os valores sorteados foram: ', end='')
for c in range(0, len(tupla)):
    print(f'{tupla[c]} ', end ='')
'''
    if c == 0:
        maior = tupla[c]
        menor = tupla[c]
    if tupla[c] >= maior:
        maior = tupla[c]
    if tupla[c] <= menor:
        menor = tupla[c]
print(f'\nO maior valor sorteado foi {maior}\nO menor valor sorteado foi {menor}')
'''

print(f'\nO maior valor sorteado foi {max(tupla)}') # método para listas e tuplas
print(f'O menor valor sorteado foi {min(tupla)}') # método para listas e tuplas

Os valores sorteados foram: 10 1 7 8 3 
O maior valor sorteado foi 10
O menor valor sorteado foi 1


69. Desenvolva um programa que leia quatro valores pelo teclado e guarde-os em uma tupla. No final, mostre:
- Quantas vezes apareceu o valor 9
- Em que posição foi digitado o primeiro valor 3
- Quais foram os números pares

In [25]:
numeros = (
    int(input('Digite um número: ')),
    int(input('Digite outro número: ')),
    int(input('Digite mais um número: ')),
    int(input('Digite o último número: '))
)

print(f'Você digitou os valores {numeros}')

print(f'O valor 9 apareceu {numeros.count(9)} vezes')

if 3 in numeros:
    print(f'O valor 3 apareceu na {numeros.index(3)+1}ª posição')
else:
    print('O valor 3 não foi digitado em nenhuma posição')

print('Os valores pares digitados foram ', end='')
for pares in numeros:
    if pares % 2 == 0:
        print(f'{pares} ', end='')

Digite um número: 9
Digite outro número: 3
Digite mais um número: 2
Digite o último número: 9
Você digitou os valores (9, 3, 2, 9)
O valor 9 apareceu 2 vezes
O valor 3 apareceu na 2ª posição
Os valores pares digitados foram 2 

70. Crie um programa que tenha uma tupla única com nomes de produtos e seus respectivos preços, na sequência. No final, mostre a listagem de preços organizando os dados de forma tabular.

In [19]:
lista = ('Lápis', 1.75, 'Borracha', 2, 'Caderno', 15.90,
         'Estojo', 25, 'Transferidor', 4.20, 'Compasso', 9.99,
         'Mochila', 120.32, 'Canetas', 22.30, 'Livro', 34.90)

print('-'*40)
print(f'{"LISTA DE PREÇOS":^40}')
print('-'*40)

for i in range(0, len(lista)):
    if i % 2 == 0:
        print(f'{lista[i]:.<30}R${lista[i+1]:>7.2f}')
print('-'*40)

----------------------------------------
            LISTA DE PREÇOS             
----------------------------------------
Lápis.........................R$   1.75
Borracha......................R$   2.00
Caderno.......................R$  15.90
Estojo........................R$  25.00
Transferidor..................R$   4.20
Compasso......................R$   9.99
Mochila.......................R$ 120.32
Canetas.......................R$  22.30
Livro.........................R$  34.90
----------------------------------------


71. Crie um programa que tenha uma tupla com várias palavras (não usar acentos). Depois disso, você deve mostrar, para cada palavra, quais são as suas vogais.

In [26]:
palavras = ('aprender', 'programar', 'linguagem', 'python',
            'curso', 'gratis', 'estudar', 'praticar',
            'trabalhar', 'mercado', 'programador', 'futuro')

for palavra in palavras:
    print(f'\nNa palavra {palavra.upper()} temos ', end='')
    for vogal in palavra:
        if vogal.lower() in 'aeiou':
            print(f'{vogal} ', end='')


Na palavra APRENDER temos a e e 
Na palavra PROGRAMAR temos o a a 
Na palavra LINGUAGEM temos i u a e 
Na palavra PYTHON temos o 
Na palavra CURSO temos u o 
Na palavra GRATIS temos a i 
Na palavra ESTUDAR temos e u a 
Na palavra PRATICAR temos a i a 
Na palavra TRABALHAR temos a a a 
Na palavra MERCADO temos e a o 
Na palavra PROGRAMADOR temos o a a o 
Na palavra FUTURO temos u u o 

72. A partir da mesma lista de palavras do exercício anterior, crie um programa que armazene todas as vogais geradas em uma tupla, utilizando tuple comprehension. No final, mostre a quantidade de cada vogal.

In [48]:
palavras = ('aprender', 'programar', 'linguagem', 'python',
            'curso', 'gratis', 'estudar', 'praticar',
            'trabalhar', 'mercado', 'programador', 'futuro')

vogais = tuple(letra for palavra in palavras for letra in palavra if letra.lower() in 'aeiou')

print(f'''letras a: {vogais.count('a')}
letras e: {vogais.count('e')}
letras i: {vogais.count('i')}
letras o: {vogais.count('o')}
letras u: {vogais.count('u')}''')

letras a: 14
letras e: 5
letras i: 3
letras o: 7
letras u: 5


73. João possui duas calças (uma calça de linho preta e uma calça jeans) e cinco camisas (social bege, social azul, camiseta branca, camiseta cinza e camiseta preta). Sabendo que João nunca deve usar camiseta com calça de linho, há quantas formas de João se vestir? Utilize tupple comprehension para fazer as combinações.

Dica: Inicie o programa com 3 tuplas: calças, camisas sociais e camisetas.

In [55]:
calcas = ('calça preta', 'calça jeans')
camisas = ('social bege', 'social azul')
camisetas = ('camiseta branca', 'camiseta cinza', 'camiseta preta')

combinacao1 = tuple((calca, camisa) for calca in calcas for camisa in camisas)
combinacao2 = tuple((calca, camiseta) for calca in calcas for camiseta in camisetas if calca != 'calça preta')

print(f'Há {len(combinacao1) + len(combinacao2)} formas de João se vestir.')

Há 7 formas de João se vestir.


74. Pedro resolveu pintar sua casa e para isso ele deve escolher duas cores de tinta, uma para o teto e outra para as paredes. Mas na loja de tintas há 3 opções de cores (branco, cinza e amarelo) as quais Pedro gostou e que servem tanto para o teto como para as paredes. Utilizando tuple comprehension, gere todas as possibilidades de pintura dessa casa.

Dica: Trata-se de um arranjo em que a resposta são 6 possibilidades. Formato da resposta: (('branco, 'cinza'), ..., ('amarelo', 'cinza')).

In [75]:
cores = ('branco', 'cinza', 'amarelo')

arranjo = tuple((cor1,cor2) for cor1 in cores for cor2 in cores if cor1 != cor2)

print(arranjo)

(('branco', 'cinza'), ('branco', 'amarelo'), ('cinza', 'branco'), ('cinza', 'amarelo'), ('amarelo', 'branco'), ('amarelo', 'cinza'))


75. Pedro, Bia e Ana foram ao cinema e compraram três cadeiras em sequência. De quantas maneiras diferentes eles podem sentar-se nessas cadeiras? Utilizando tuple comprehension gere todas as possibilidades.

Dica: Trata-se de uma permutação. Formato da resposta: (('Pedro', 'Bia', 'Ana'), ..., ('Ana', 'Bia', 'Pedro'))

In [12]:
pessoas = ('Pedro', 'Bia', 'Ana')

permutacao = tuple((p1,p2,p3) for p1 in pessoas for p2 in pessoas for p3 in pessoas if p1 != p2 and p1 != p3 and p2 != p3)

print(f'A quantidade de maneiras distintas que eles podem sentar-se é {len(permutacao)}.')
print(permutacao)

A quantidade de maneiras distintas que eles podem sentar-se é 6.
(('Pedro', 'Bia', 'Ana'), ('Pedro', 'Ana', 'Bia'), ('Bia', 'Pedro', 'Ana'), ('Bia', 'Ana', 'Pedro'), ('Ana', 'Pedro', 'Bia'), ('Ana', 'Bia', 'Pedro'))


76. Um grupo de cinco amigos (Pedro, Bia, Ana, Carlos e Maria) foram para praia jogar volei de areia em duplas. A partir desse grupo, é possível formar quantas duplas distintas? Use tuple comprehension para gerar as possibilidades.

Dica: Trata-se de uma combinação. Formato da resposta: (('Pedro', 'Bia'), ..., ('Carlos', 'Maria'))

In [78]:
grupo = ('Pedro', 'Bia', 'Ana', 'Carlos', 'Maria')

#duplas = tuple((grupo[i],grupo[j]) for i in range(0, len(grupo)) for j in range(0, len(grupo)) if i < j)
duplas = tuple((p1,p2) for i, p1 in enumerate(grupo) for j, p2 in enumerate(grupo) if i < j)

print(f'É possível formar {len(duplas)} duplas distintas')
print(duplas)

É possível formar 10 duplas distintas
(('Pedro', 'Bia'), ('Pedro', 'Ana'), ('Pedro', 'Carlos'), ('Pedro', 'Maria'), ('Bia', 'Ana'), ('Bia', 'Carlos'), ('Bia', 'Maria'), ('Ana', 'Carlos'), ('Ana', 'Maria'), ('Carlos', 'Maria'))


77. Utilizando generator comprehension, gere as tabuadas de 7, 8 e 9 lado a lado.

In [81]:
tabuadas = (f'7 x {i} = {7*i} | 8 x {i} = {8*i} | 9 x {i} = {9*i}' for i in range(1, 11))

for linha in tabuadas:
    print(linha)

7 x 1 = 7 | 8 x 1 = 8 | 9 x 1 = 9
7 x 2 = 14 | 8 x 2 = 16 | 9 x 2 = 18
7 x 3 = 21 | 8 x 3 = 24 | 9 x 3 = 27
7 x 4 = 28 | 8 x 4 = 32 | 9 x 4 = 36
7 x 5 = 35 | 8 x 5 = 40 | 9 x 5 = 45
7 x 6 = 42 | 8 x 6 = 48 | 9 x 6 = 54
7 x 7 = 49 | 8 x 7 = 56 | 9 x 7 = 63
7 x 8 = 56 | 8 x 8 = 64 | 9 x 8 = 72
7 x 9 = 63 | 8 x 9 = 72 | 9 x 9 = 81
7 x 10 = 70 | 8 x 10 = 80 | 9 x 10 = 90


78. Faça um programa que leia 5 valores numéricos e guarde em uma lista. No final, mostre qual foi o maior e o menor valor digitados e as suas respectivas posições.

In [13]:
valores = []

for v in range(0, 5):
    valores.append(int(input(f'Digite um valor para a posição {v}: ')))
print('=-'*30)
print(f'Você digitou os valores {valores}')
print()

maior = max(valores)
menor = min(valores)

print(f'O maior valor digitado foi {maior} nas posições ', end='')
for pos, valor in enumerate(valores):
    if valor == maior:
        print(f'{pos}.. ', end='')

print(f'\nO menor valor digitado foi {menor} nas posições ', end='')
for pos, valor in enumerate(valores):
    if valor == menor:
        print(f'{pos}.. ', end='')

Digite um valor para a posição 0: 1
Digite um valor para a posição 1: 2
Digite um valor para a posição 2: 1
Digite um valor para a posição 3: 5
Digite um valor para a posição 4: 5
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Você digitou os valores [1, 2, 1, 5, 5]

O maior valor digitado foi 5 nas posições 3.. 4.. 
O menor valor digitado foi 1 nas posições 0.. 2.. 

79. Crie um programa onde o usuário possa digitar vários valores numéricos e cadastre-os em uma lista. Caso o número já exista lá dentro, ele não será adicionado. No final, serão exibidos todos os **valores únicos** digitados, em ordem crescente.

In [120]:
valores = []

while True:
    num = int(input('Digite um valor: '))
    if num not in valores:
        valores.append(num)
        print('Valor adicionado com sucesso...')
    else:
        print('Valor duplicado! Não vou adicionar...')
    
    resp = ' '
    while resp not in 'SN':
        resp = str(input('Quer continuar? [S/N]')).upper().strip()[0]
    if resp == 'N':
        break

valores.sort()
print('-='*20)
print(f'Você digitou os valores {valores}')

Digite um valor: 5
Valor adicionado com sucesso...
Quer continuar? [S/N]s
Digite um valor: 9
Valor adicionado com sucesso...
Quer continuar? [S/N]s
Digite um valor: 3
Valor adicionado com sucesso...
Quer continuar? [S/N]9
Quer continuar? [S/N]s
Digite um valor: 9
Valor duplicado! Não vou adicionar...
Quer continuar? [S/N]s
Digite um valor: 3
Valor duplicado! Não vou adicionar...
Quer continuar? [S/N]s
Digite um valor: 7
Valor adicionado com sucesso...
Quer continuar? [S/N]n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Você digitou os valores [3, 5, 7, 9]


In [14]:
# menos eficiente

valores = []
index = -1

while True:
    valores.append(int(input('Digite um valor: ')))
    
    index += 1
    if valores.count(valores[index]) > 1:
        valores.pop()
        index -= 1
        print('Valor duplicado! Não vou adicionar...')
    else:
        print('Valor adicionado com sucesso...')
    
    resp = ' '
    while resp not in 'SN':
        resp = str(input('Quer continuar? [S/N]')).upper().strip()[0]
    if resp == 'N':
        break

valores.sort()
print('-='*20)
print(f'Você digitou os valores {valores}')

Digite um valor: 5
Valor adicionado com sucesso...
Quer continuar? [S/N]s
Digite um valor: 9
Valor adicionado com sucesso...
Quer continuar? [S/N]3
Quer continuar? [S/N]s
Digite um valor: 3
Valor adicionado com sucesso...
Quer continuar? [S/N]s
Digite um valor: 9
Valor duplicado! Não vou adicionar...
Quer continuar? [S/N]s
Digite um valor: 3
Valor duplicado! Não vou adicionar...
Quer continuar? [S/N]s
Digite um valor: 7
Valor adicionado com sucesso...
Quer continuar? [S/N]n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Você digitou os valores [3, 5, 7, 9]


80. Crie um programa onde o usuário possa digitar 5 valores numéricos e cadastre-os em uma lista, já na posição correta de inserção (sem usar o sort()). No final, mostre a lista ordenada na tela.

In [139]:
valores = []

for i in range(0, 5):
    num = int(input(f'Digite um valor: '))
    
    if i == 0 or num > valores[-1]: # lista[-1] é o último elemento da lista
        valores.append(n)
        print('Adicionado ao final da lista...')
    else:
        for pos, valor in enumerate(valores): # percorre a lista para comparar
            if num <= valor:
                valores.insert(pos, num)
                print(f'Adicionado na posição {pos}...')
                break

print('-='*30)
print(f'Os valores digitados em ordem foram {valores}')

Digite um valor: 9
Adicionado ao final da lista...
Digite um valor: 1
Adicionado na posição 0...
Digite um valor: 8
Adicionado na posição 1...
Digite um valor: 2
Adicionado na posição 1...
Digite um valor: 5
Adicionado na posição 2...
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Os valores digitados em ordem foram [1, 2, 5, 8, 9]


81. Crie um programa que vai ler vários números e colocar em uma lista. Depois disso, mostre:
- Quantos números foram digitados.
- Lista de valores, ordenada de forma decrescente. 
- Se o valor 5 foi digitado e está ou não na lista.

In [4]:
lista = []

while True:
    lista.append(int(input('Digite um valor: ')))
    
    resp = ' '
    while resp not in 'SN':
        resp = str(input('Quer continuar? [S/N] ')).upper().strip()[0]
    if resp == 'N':
        break

print('-='*30)
print(f'Você digitou {len(lista)} elementos')

lista.sort(reverse=True)
print(f'Os valores em ordem descrescente são {lista}')

if 5 in lista:
    print('O valor 5 faz parte da lista!')
else:
    print('O valor 5 não foi encontrado na lista!')

Digite um valor: 9
Quer continuar? [S/N] s
Digite um valor: 3
Quer continuar? [S/N] s
Digite um valor: 2
Quer continuar? [S/N] n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Você digitou 3 elementos
Os valores em ordem descrescente são [9, 3, 2]
O valor 5 não foi encontrado na lista!


82. Crie um programa que vai ler vários números e colocar em uma lista. Depois disso, crie duas listas extras que vão conter apenas os valores pares e os valores ímpares, digitados respectivamente. Ao final, mostre o conteúdo das três listas geradas.

Obs.: Não alimente as três listas já no primeiro laço. Leia a primeira para gerar as outras duas.

In [16]:
valores = []
pares = []
impares = []

while True:
    valores.append(int(input('Digite um valor: ')))
    resp = ' '
    
    while resp not in 'SN':
        resp = str(input('Quer continuar? [S/N] ')).upper().strip()[0]
    if resp == 'N':
        break

for valor in valores:
    if valor % 2 == 0:
        pares.append(valor)
    elif valor % 2 == 1:
        impares.append(valor)

print('-='*30)
print(f'A lista completa é {valores}')
print(f'A lista de pares é {pares}')
print(f'A lista de ímpares é {impares}')

Digite um valor: 5
Quer continuar? [S/N] s
Digite um valor: 9
Quer continuar? [S/N] s
Digite um valor: 2
Quer continuar? [S/N] s
Digite um valor: 6
Quer continuar? [S/N] s
Digite um valor: 13
Quer continuar? [S/N] n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
A lista completa é [5, 9, 2, 6, 13]
A lista de pares é [2, 6]
A lista de ímpares é [5, 9, 13]


83. Crie um programa onde o usuário digite uma expressão matemática qualquer que use parênteses. Seu aplicativo deverá analisar se a expressão passada está com os parênteses abertos e fechados na ordem correta.

In [24]:
exp = str(input('Digite uma expressão: '))
aberto = fechado = 0

for p in exp:
    if p == '(':
        aberto += 1
    elif p == ')':
        fechado += 1
        
    if fechado > aberto: # quando fechado ficar maior que aberto, ele quebra
        break
        
if aberto == fechado:
    print('Sua expressão está válida!')
else:
    print('Sua expressão está errada!')

Digite uma expressão: (a-a)*(A)/(b+c)
Sua expressão está válida!


In [13]:
exp = str(input('Digite uma expressão: '))
pilha = []

for p in exp:
    if p == '(':
        pilha.append('(') # adiciona '(' à lista
    elif p == ')':
        if len(pilha) > 0:
            pilha.pop() # retira '(' da lista
        else:
            pilha.append(')') # adiciona ')' à lista zerada
            break # interrompe o loop pois encontrou erro

if len(pilha) == 0:
    print('Sua expressão está válida!') # retirou todos '('
else:
    print('Sua expressão está errada!')

Digite uma expressão: (a-a)*(A)/(b+c)
Sua expressão está válida!


84. Crie um programa que gere uma lista, utilizando list comprehension, com os números ímpares de 1 a 50 que são divisíveis por 3.

In [82]:
impares_3 = [num for num in range(1,51) if num % 2 != 0 and num % 3 == 0]
print(impares_3)

[3, 9, 15, 21, 27, 33, 39, 45]


85. Faça um programa que leia nome e peso de várias pessoas, guardando tudo em uma lista. No final, mostre:
- Quantas pessoas foram cadastradas
- Uma lista com as pessoas mais pesadas
- Uma lista com as pessoas mais leves

In [1]:
dado = list()
pessoas = list()

while True:    
    dado.append(str(input('Nome: ')).strip())
    dado.append(float(input('Peso (Kg): ')))
    
    if len(pessoas) == 0:
        maior = menor = dado[1]
    else:
        if dado[1] > maior:
            maior = dado[1]
        if dado[1] < menor:
            menor = dado[1]
            
    pessoas.append(dado[:])
    dado.clear()
    
    resp = ' '
    while resp not in 'SN':
        resp = str(input('Quer continuar? [S/N] ')).upper().strip()[0]
    if resp == 'N':
        break
        
print('-='*30)
print(f'Ao todo, você cadastrou {len(pessoas)} pessoas')

print(f'O maior peso foi de {maior:.1f}Kg. Peso de ', end='')
for pessoa in pessoas:
    if pessoa[1] == maior:
        print(f'[{pessoa[0]}] ', end='')
print()

print(f'O menor peso foi de {menor:.1f}Kg. Peso de ', end='')
for pessoa in pessoas:
    if pessoa[1] == menor:
        print(f'[{pessoa[0]}] ', end='')

Nome: Ana
Peso (Kg): 75.5
Quer continuar? [S/N] s
Nome: Pedro
Peso (Kg): 89.2
Quer continuar? [S/N] s
Nome: Joana
Peso (Kg): 89.2
Quer continuar? [S/N] s
Nome: Carol
Peso (Kg): 42.3
Quer continuar? [S/N] s
Nome: Maria
Peso (Kg): 50.4
Quer continuar? [S/N] s
Nome: Bianca
Peso (Kg): 42.3
Quer continuar? [S/N] s
Nome: Artur
Peso (Kg): 75.5
Quer continuar? [S/N] n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Ao todo, você cadastrou 7 pessoas
O maior peso foi de 89.2Kg. Peso de [Pedro] [Joana] 
O menor peso foi de 42.3Kg. Peso de [Carol] [Bianca] 

86. Crie um programa no qual o usuário possa digitar sete valores numéricos e cadastre-os em uma lista única que mantenha separados os valores pares e ímpares. No final, mostre os valores pares e ímpares em ordem crescente.

In [2]:
lista_composta = [[], []]

for c in range(0, 7):
    num = int(input(f'Digite o {c+1}º valor: '))
    if num % 2 == 0:
        lista_composta[0].append(num)
    else:
        lista_composta[1].append(num)

lista_composta[0].sort()
lista_composta[1].sort()
print(f'Pares: {lista_composta[0]}')
print(f'Ímpares: {lista_composta[1]}')

Digite o 1º valor: 9
Digite o 2º valor: 1
Digite o 3º valor: 5
Digite o 4º valor: 6
Digite o 5º valor: 8
Digite o 6º valor: 3
Digite o 7º valor: 2
Pares: [2, 6, 8]
Ímpares: [1, 3, 5, 9]


87. Crie um programa que declare uma matriz de dimensão 3×3 e preencha com valores lidos pelo teclado. No final, mostre a matriz na tela, com a formatação correta.

In [3]:
matriz = [[], [], []]

for linha in range(0, 3):
    for coluna in range(0, 3):
        num = int(input(f'Digite um valor para [{linha}, {coluna}]: '))
        matriz[linha].append(num)

print('-='*30)

for linha in range(0, 3):
    for coluna in range(0, 3):
        print(f'[{matriz[linha][coluna]:^5}] ', end='') # três colunas na mesma linha
    print() # quebra linha

Digite um valor para [0, 0]: 1
Digite um valor para [0, 1]: 2
Digite um valor para [0, 2]: 3
Digite um valor para [1, 0]: 4
Digite um valor para [1, 1]: 5
Digite um valor para [1, 2]: 6
Digite um valor para [2, 0]: 7
Digite um valor para [2, 1]: 8
Digite um valor para [2, 2]: 9
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[  1  ] [  2  ] [  3  ] 
[  4  ] [  5  ] [  6  ] 
[  7  ] [  8  ] [  9  ] 


88. Aprimore o desafio anterior, mostrando no final:
- A soma de todos os valores pares digitados.
- A soma dos valores da terceira coluna.
- O maior valor da segunda linha.

In [4]:
matriz = [[], [], []]
somapar = somacol = 0

for linha in range(0, 3):
    for coluna in range(0, 3):
        num = int(input(f'Digite o valor para [{linha}, {coluna}]: '))
        matriz[linha].append(num)
        if num % 2 == 0:
            somapar += num
        if coluna == 2:
            somacol += num
        if linha == 1 and coluna == 0:
            maior = matriz[linha][coluna]
        else:
            if linha == 1 and matriz[linha][coluna] > maior:
                maior = matriz[linha][coluna]

print('-='*30)

for linha in range(0, 3):
    for coluna in range(0,3):
        print(f'[{matriz[linha][coluna]:^5}] ', end='') # três colunas na mesma linha
    print() # quebra de linha

print('-='*30)
print(f'A soma dos valores pares é {somapar}')
print(f'A soma dos valores da terceira coluna é {somacol}')
print(f'O maior valor da segunda linha é {maior}')

Digite o valor para [0, 0]: 1
Digite o valor para [0, 1]: 2
Digite o valor para [0, 2]: 3
Digite o valor para [1, 0]: 4
Digite o valor para [1, 1]: 5
Digite o valor para [1, 2]: 6
Digite o valor para [2, 0]: 7
Digite o valor para [2, 1]: 8
Digite o valor para [2, 2]: 9
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[  1  ] [  2  ] [  3  ] 
[  4  ] [  5  ] [  6  ] 
[  7  ] [  8  ] [  9  ] 
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
A soma dos valores pares é 20
A soma dos valores da terceira coluna é 18
O maior valor da segunda linha é 6


89. A partir de uma lista composta (matriz) com as mesma quantidade de elementos pares e ímpares ([[6,8,2],[9,1,5]]) imprima uma tabela com duas colunas (pares e ímpares) em ordem decrescente, utilizando a função tabulate.

Dica 1: from tabulate import tabulate</br>
Dica 2: você precisará calcular a matriz transposta

In [12]:
from tabulate import tabulate

matriz = [[6,8,2],[9,1,5]]

matriz[0].sort(reverse=True)
matriz[1].sort(reverse=True)

mtransposta = [[linha[i] for linha in matriz] for i in range(3)] # matriz transposta

tabulate(mtransposta, headers=['Pares', 'Ímpares'], tablefmt='html')

'<table>\n<thead>\n<tr><th style="text-align: right;">  Pares</th><th style="text-align: right;">  Ímpares</th></tr>\n</thead>\n<tbody>\n<tr><td style="text-align: right;">      8</td><td style="text-align: right;">        9</td></tr>\n<tr><td style="text-align: right;">      6</td><td style="text-align: right;">        5</td></tr>\n<tr><td style="text-align: right;">      2</td><td style="text-align: right;">        1</td></tr>\n</tbody>\n</table>'

90. Faça um programa que ajude um jogador da Mega-Sena a criar palpites. O programa vai perguntar quantos jogos serão gerados e vai sortear 6 números entre 1 e 60 para cada jogo, cadastrando tudo em uma lista composta.

In [6]:
from random import randint
from time import sleep

lista = []
cartela = []

print('-'*30)
print(f'{"JOGAR NA MEGA SENA":^30}')
print('-'*30)
jogos = int(input('Quantos jogos você quer que eu sorteie? '))
print('-='*3, f'SORTEANDO {jogos} JOGOS', '-='*3)

for c in range(0, jogos):
    for num in range(6): # 6 números para cada jogo
        
        while True:
            cartela.append(randint(1, 60))
            if cartela.count(cartela[num]) > 1: # se o número já foi marcado
                cartela.pop()
            else:
                break # se o numero não for repetido
                
    cartela.sort()
    lista.append(cartela[:])
    cartela.clear()
    sleep(1)
    print(f'Jogo {c+1}: {lista[c]}')
print('-='*5, '< BOA SORTE >', '-='*5)

------------------------------
      JOGAR NA MEGA SENA      
------------------------------
Quantos jogos você quer que eu sorteie? 5
-=-=-= SORTEANDO 5 JOGOS -=-=-=
Jogo 1: [9, 21, 23, 40, 47, 55]
Jogo 2: [16, 21, 24, 45, 54, 55]
Jogo 3: [4, 8, 11, 28, 30, 45]
Jogo 4: [3, 10, 25, 44, 50, 51]
Jogo 5: [19, 24, 25, 33, 38, 51]
-=-=-=-=-= < BOA SORTE > -=-=-=-=-=


In [7]:
from random import sample
from time import sleep

lista =[]

print('-'*30)
print(f'{"JOGAR NA MEGA SENA":^30}')
print('-'*30)

jogos = int(input('Quantos jogos você quer que eu sorteie? '))

print('-='*3, f'SORTEANDO {jogos} JOGOS', '-='*3)

for c in range(jogos):
    cartela = sample(range(1, 60), 6) # amostra de 6 números
    cartela.sort()
    lista.append(cartela[:])
    cartela.clear()
    sleep(1)
    print(f'Jogo {c+1}: {lista[c]}')
    sleep(1)
    
print('-='*5, '< BOA SORTE >', '-='*5)

------------------------------
      JOGAR NA MEGA SENA      
------------------------------
Quantos jogos você quer que eu sorteie? 5
-=-=-= SORTEANDO 5 JOGOS -=-=-=
Jogo 1: [4, 27, 35, 45, 52, 59]
Jogo 2: [7, 21, 25, 37, 45, 46]
Jogo 3: [9, 14, 32, 36, 38, 57]
Jogo 4: [2, 10, 17, 21, 38, 53]
Jogo 5: [12, 21, 24, 25, 50, 54]
-=-=-=-=-= < BOA SORTE > -=-=-=-=-=


91. Crie um programa que leia nome e duas notas de vários alunos e guarde em uma lista composta. No final, mostre um boletim contendo a média de cada um e permita que o usuário possa mostrar as notas de cada aluno individualmente.

In [3]:
lista = []
ficha = []
notas = []

while True:
    ficha.append(str(input('Nome: ')).strip()) # nome na ficha
    
    for n in range(2):
        notas.append(float(input(f'Nota {n+1}: ')))
    
    ficha.append(notas[:]) # notas na ficha
    media = (notas[0] + notas[1])/2
    ficha.append(media) # média na ficha
    lista.append(ficha[:]) # ficha na lista
    notas.clear()
    ficha.clear()
    
    resp = ' '
    while resp not in 'SN':
        resp = str(input('Quer continuar? [S/N]')).upper().strip()[0]
    if resp == 'N':
        break
        
print('-='*30)
print(f'{"Nº":<4}{"NOME":<10}{"MÉDIA":>8}')
print('-'*26)
for c in range(0, len(lista)):
    print(f'{c:<4}{lista[c][0]:<10}{lista[c][2]:>8.1f}') # lista[c][0] é nome e lista[c][2] é média

while True:
    print('-'*35)
    opc = int(input('Mostrar notas de qual aluno? (999 interrompe)'))
    if opc == 999: #flag
        print('FINALIZANDO...')
        break
    if opc < len(lista):
        print(f'As notas de {lista[opc][0]} são {lista[opc][1]}')

print('<<< VOLTE SEMPRE >>>')

Nome: Ana
Nota 1: 10
Nota 2: 9.5
Quer continuar? [S/N]s
Nome: Gustavo
Nota 1: 2.5
Nota 2: 4
Quer continuar? [S/N]s
Nome: Pedro
Nota 1: 5.5
Nota 2: 8
Quer continuar? [S/N]s
Nome: João
Nota 1: 8
Nota 2: 3
Quer continuar? [S/N]n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Nº  NOME         MÉDIA
--------------------------
0   Ana            9.8
1   Gustavo        3.2
2   Pedro          6.8
3   João           5.5
-----------------------------------
Mostrar notas de qual aluno? (999 interrompe)0
As notas de Ana são [10.0, 9.5]
-----------------------------------
Mostrar notas de qual aluno? (999 interrompe)2
As notas de Pedro são [5.5, 8.0]
-----------------------------------
Mostrar notas de qual aluno? (999 interrompe)999
FINALIZANDO...
<<< VOLTE SEMPRE >>>


In [1]:
ficha = list()

while True:
    nome = str(input('Nome: '))
    nota1 = float(input('Nota 1: '))
    nota2 = float(input('Nota 2: '))
    media = (nota1 + nota2)/2
    ficha.append([nome, [nota1, nota2], media])
    
    resp = ' '
    while resp not in 'SN':
        resp = str(input('Quer continuar? [S/N]')).upper().strip()[0]
    if resp == 'N':
        break

print('-='*30)
print(f'{"Nº":<4}{"NOME":<10}{"MÉDIA":>8}')
print('-'*26)
for index, aluno in enumerate(ficha):
    print(f'{index:<4}{aluno[0]:<10}{aluno[2]:>8.1f}') # aluno[0] é nome, aluno[1] é lista com notas e aluno[2] é média

while True:
    print('-'*35)
    opc = int(input('Mostrar notas de qual aluno? (999 interrompe)'))
    if opc == 999: #flag
        print('FINALIZANDO...')
        break
    if opc < len(ficha):
        print(f'As notas de {ficha[opc][0]} são {ficha[opc][1]}') #ficha[][0] é nome e ficha[][1] é lista com notas

print('<<< VOLTE SEMPRE >>>')

Nome: Ana
Nota 1: 10
Nota 2: 9.5
Quer continuar? [S/N]s
Nome: Gustavo
Nota 1: 2.5
Nota 2: 4
Quer continuar? [S/N]s
Nome: Pedro
Nota 1: 5.5
Nota 2: 8
Quer continuar? [S/N]s
Nome: João
Nota 1: 8
Nota 2: 3
Quer continuar? [S/N]n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Nº  NOME         MÉDIA
--------------------------
0   Ana            9.8
1   Gustavo        3.2
2   Pedro          6.8
3   João           5.5
-----------------------------------
Mostrar notas de qual aluno? (999 interrompe)0
As notas de Ana são [10.0, 9.5]
-----------------------------------
Mostrar notas de qual aluno? (999 interrompe)2
As notas de Pedro são [5.5, 8.0]
-----------------------------------
Mostrar notas de qual aluno? (999 interrompe)999
FINALIZANDO...
<<< VOLTE SEMPRE >>>


92. Crie um programa com uma lista composta, utilizando list comprehension, em que dentro dela tenha:
- Uma lista de números ímpares entre 1 e 10
- Uma lista que mostre o quadrado dos números entre 1 e 5
- Uma lista de números entre 1 e 10 que sejam maiores de 5
- Uma lista contendo os 5 primeiros termos de uma PA de razão 3, onde o primeiro termo é 8.

Ao final, mostre a lista composta e itere sobre ela mostrando quantos números 9 há.

In [20]:
from tabulate import tabulate

matriz = [[num for num in range(1, 11) if num % 2 != 0],
          [num**2 for num in range(1, 6)], 
          [num for num in range(1,11) if num > 5],
          [num for num in range(8,8+4*3+1,3)] # [a1, a1 + 4*r + 1, r]
]

mtransposta = [[linha[i] for linha in matriz] for i in range(5)]
print(tabulate(mtransposta, headers=['Ímpares', 'Quadrado', 'num > 5', 'Prog. Aritm.'], tablefmt='plan'))

soma = 0

for lista in range(len(matriz)):
    soma += matriz[lista].count(9)
print(f'Foram encontrados {soma} números 9 no total.')

  Ímpares    Quadrado    num > 5    Prog. Aritm.
---------  ----------  ---------  --------------
        1           1          6               8
        3           4          7              11
        5           9          8              14
        7          16          9              17
        9          25         10              20
Foram encontrados 3 números 9 no total.


93. Crie um programa que leia as listas do exercício anterior e concatene-as. No final, mostre uma lista de números distintos (sem repetição) formada somente com os números dessas listas.

In [14]:
matriz = [[num for num in range(1, 11) if num % 2 != 0],
          [num**2 for num in range(1, 6)], 
          [num for num in range(1,11) if num > 5],
          [num for num in range(8,8+4*3+1,3)] # [a1, a1 + 4*r + 1, r]
] 

print(matriz)

nova_lista = []

for lista in matriz:
    nova_lista += lista
print(list(set(nova_lista)))

[[1, 3, 5, 7, 9], [1, 4, 9, 16, 25], [6, 7, 8, 9, 10], [8, 11, 14, 17, 20]]
[1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 14, 16, 17, 20, 25]


94. Crie um programa que faça uma pesquisa com 8 alunos de uma escola, numerando-os. O programa fará 3 perguntas: se ele gosta de estudar programação, se ele gosta de estudar matemática e se ele gosta de estudar inglês. O número do aluno deve ser armazenada nas listas programação, matemática e inglês respectivamente, de acordo com suas respostas. Ao final mostre:
- Quantos alunos gostam de Programação
- Quantos alunos gostam de Matemática
- Quantos alunos gostam de Inglês
- Quantos alunos gostam de programação e Matemática
- Quantos alunos gostam de Programação e Inglês
- Quantos alunos gostam de Matemática e Inglês
- Quantos alunos gostam das três disciplinas
- Quantos alunos não gostam de nenhuma disciplina
- Quantos alunos gostam somente de Programação
- Quantos alunos gostam somente de Matemática
- Quantos alunos gostam somente de Inglês

In [23]:
programacao = set()
matematica = set()
ingles = set()

print('-='*20)
for aluno in range(1, 9):
    print(f'Cadastrando as respostas do {aluno}º aluno..')
        
    resp = ' '
    while resp not in 'SN':
        resp = str(input('Gosta de Programação? [S/N]')).upper().strip()[0]
    if resp == 'S':
        programacao.add(aluno)
        
    resp = ' '
    while resp not in 'SN':
        resp = str(input('Gosta de Matemática? [S/N]')).upper().strip()[0]
    if resp == 'S':
        matematica.add(aluno)
        
    resp = ' '
    while resp not in 'SN':
        resp = str(input('Gosta de Inglês? [S/N]')).upper().strip()[0]
    if resp == 'S':
        ingles.add(aluno)
    
    print('-='*20)

print(f'{len(programacao)} alunos que gostam de Programação: {programacao}')
print(f'{len(matematica)} alunos que gostam de Matemática: {matematica}')
print(f'{len(ingles)} alunos que gostam de Inglês: {ingles}')

programacao_e_matematica = programacao & matematica
# programacao_e_matematica = programacao.intersection(matematica)
programacao_e_ingles = programacao & ingles
# programacao_e_ingles = programacao.intersection(ingles)
matematica_e_ingles = matematica & ingles
# matematica_e_ingles = matematica.intersection(ingles)

print(f'{len(programacao_e_matematica)} alunos que gostam de Programação e Matemática: {programacao_e_matematica}')
print(f'{len(programacao_e_ingles)} alunos que gostam de Programação e Inglês: {programacao_e_ingles}')
print(f'{len(matematica_e_ingles)} alunos que gostam de Matemática e Inglês: {matematica_e_ingles}')

tres_disciplinas = programacao & matematica & ingles
tres_disciplinas = programacao.intersection(matematica.intersection(ingles))
# tres_disciplinas = programacao_e_matematica.intersection(ingles)

print(f'{len(tres_disciplinas)} alunos que gostam das três disciplinas: {tres_disciplinas}')

nenhuma = 8 - len(programacao | matematica | ingles)
# nenhuma = 8 - len(programacao.union(matematica.union(ingles))) 
# nenhuma = 8 - len(set(list(programacao) + list(matematica) + list(ingles)))

print(f'{nenhuma} alunos não gostam de nenhuma disciplina') 

somente_programacao = (programacao - matematica) - ingles
somente_matematica = (matematica - programacao) - ingles
somente_ingles = (ingles - programacao) - matematica

print(f'{len(somente_programacao)} alunos gostam somente de Programação')
print(f'{len(somente_matematica)} alunos gostam somente de Matemática')
print(f'{len(somente_ingles)} alunos gostam somente de Inglês')

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Cadastrando as respostas do 1º aluno..
Gosta de Programação? [S/N]s
Gosta de Matemática? [S/N]s
Gosta de Inglês? [S/N]s
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Cadastrando as respostas do 2º aluno..
Gosta de Programação? [S/N]n
Gosta de Matemática? [S/N]n
Gosta de Inglês? [S/N]n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Cadastrando as respostas do 3º aluno..
Gosta de Programação? [S/N]s
Gosta de Matemática? [S/N]n
Gosta de Inglês? [S/N]n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Cadastrando as respostas do 4º aluno..
Gosta de Programação? [S/N]n
Gosta de Matemática? [S/N]s
Gosta de Inglês? [S/N]s
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Cadastrando as respostas do 5º aluno..
Gosta de Programação? [S/N]s
Gosta de Matemática? [S/N]s
Gosta de Inglês? [S/N]n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Cadastrando as respostas do 6º aluno..
Gosta de Programação? [S/N]n
Gosta de Matemática? [S/N]n
Gosta de Inglês? [S/N]s
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

95. Faça um programa que leia nome e média de um aluno, guardando também a situação (média >= 7, aprovado) em um dicionário. No final, mostre o conteúdo da estrutura na tela.

In [16]:
ficha = dict()

ficha['nome'] = str(input('Nome: ')).strip()
ficha['media'] = float(input(f'Média de {ficha["nome"]}: '))

if ficha['media'] >= 7:
    ficha['situacao'] = 'Aprovado'
elif ficha['media'] >= 5:
    ficha['situacao'] = 'Recuperação'
else:
    ficha['situacao'] = 'Reprovado'

print('-='*30)
for k, v in ficha.items():
    print(f'  - {k} é igual a {v}')

Nome: Icaro
Média de Icaro: 5.5
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  - nome é igual a Icaro
  - media é igual a 5.5
  - situacao é igual a Recuperação


96. Crie um programa onde 4 jogadores joguem um dado e tenha resultados aleatórios. Guarde esses resultados em um dicionário. No final, coloque o dicionário em ordem, sabendo que o vencedor tirou o maior número no dado.

Dica: Se não souber ordenar um dicionário, use o ChatGPT. A função lambda é melhor explicada no notebook de funções.

In [37]:
from random import randint
from time import sleep
from operator import itemgetter #função do módulo itemgetter para ordenar dicionários

jogo = dict()
ranking = list()

for j in range(4):
    jogo[f'jogador{j+1}'] = randint(1, 6)

print('Valores sorteados:')
for k, v in jogo.items():
    print(f'O {k} tirou {v} no dado.')
    sleep(1)

ranking = sorted(jogo.items(), key = itemgetter(1), reverse = True) # 0 para chave e 1 para valor

print('-='*30)
print(f' == RANKING DOS JOGADORES ==')
for i, v in enumerate(ranking):
    print(f'  {i+1}º lugar: {v[0]} com {v[1]}.')
    sleep(1)

Valores sorteados:
O jogador1 tirou 1 no dado.
O jogador2 tirou 5 no dado.
O jogador3 tirou 1 no dado.
O jogador4 tirou 5 no dado.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 == RANKING DOS JOGADORES ==
  1º lugar: jogador2 com 5.
  2º lugar: jogador4 com 5.
  3º lugar: jogador1 com 1.
  4º lugar: jogador3 com 1.


In [38]:
from random import randint
from time import sleep

jogo = dict()
ranking = list()

for j in range(4):
    jogo[f'jogador{j+1}'] = randint(1, 6)

print('Valores sorteados:')
for k, v in jogo.items():
    print(f'O {k} tirou {v} no dado.')
    sleep(1)

# usando função lambda (no módulo de funções será melhor explicada)
ranking = sorted(jogo.items(), key = lambda item: item[1], reverse = True) # Python 3.7: não há necessidade do itemgetter

print('-='*30)
print(f' == RANKING DOS JOGADORES ==')
for i, v in enumerate(ranking):
    print(f'  {i+1}º lugar: {v[0]} com {v[1]}.')
    sleep(1)

Valores sorteados:
O jogador1 tirou 3 no dado.
O jogador2 tirou 5 no dado.
O jogador3 tirou 6 no dado.
O jogador4 tirou 2 no dado.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 == RANKING DOS JOGADORES ==
  1º lugar: jogador3 com 6.
  2º lugar: jogador2 com 5.
  3º lugar: jogador1 com 3.
  4º lugar: jogador4 com 2.


97. Crie um programa que leia **nome**, **ano de nascimento** e **carteira de trabalho** e cadastre-os (com idade) em um dicionário. Se por acaso a CTPS for diferente de ZERO, o dicionário receberá também o **ano de contratação** e o **salário**. Calcule e acrescente, além da idade, com quantos anos a pessoa vai se aposentar.

In [1]:
from datetime import datetime

ficha = dict()

ficha['nome'] = str(input('Nome: ')).strip()
nasc = int(input('Ano de Nascimento:'))
ficha['idade'] = datetime.now().year - nasc
ficha['ctps'] = int(input('Carteira de Trabalho (0 não tem): '))

if ficha['ctps'] != 0:
    ficha['contratação'] = int(input('Ano de contratação: '))
    ficha['salário'] = float(input('Salário: R$'))
    ficha['aposentadoria'] = (ficha['contratação'] + 35) - nasc

print('-='*30)
for k, v in ficha.items():
    print(f'  - {k} tem o valor {v}')

Nome: Gustavo
Ano de Nascimento:1978
Carteira de Trabalho (0 não tem): 1234
Ano de contratação: 1995
Salário: R$1000
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  - nome tem o valor Gustavo
  - idade tem o valor 45
  - ctps tem o valor 1234
  - contratação tem o valor 1995
  - salário tem o valor 1000.0
  - aposentadoria tem o valor 52


98. Crie um programa que gerencie o aproveitamento de um jogador de futebol. O programa vai ler o **nome do jogador** e **quantas partidas** ele jogou. Depois vai ler a **quantidade de gols** feitos em cada partida (guarde-os em uma lista). No final, tudo isso será guardado em um dicionário, incluindo o **total de gols** feitos durante o campeonato.

In [8]:
jogador = dict()
gols_nas_partidas = list()

jogador['nome'] = str(input('Nome do jogador: ')).strip()
tot = int(input(f'Quantas partidas {jogador["nome"]} jogou? '))

# gols em cada partida:
for g in range(0, tot):
    gols_nas_partidas.append(int(input(f'Quantos gols na partida {g+1}? ')))

jogador['gols'] = gols_nas_partidas[:]
jogador['total'] = sum(gols_nas_partidas) # soma os gols da lista

print('-='*30)
print(jogador)
print('-='*30)
for k, v in jogador.items():
    print(f'O campo {k} tem o valor {v}')

print('-='*30)
print(f'O jogador {jogador["nome"]} jogou {len(jogador["gols"])} partidas.') # poderia ter usado tot
for p, g in enumerate(gols_nas_partidas):
    print(f'  => Na partida {p+1}, fez {g} gols.')
print(f'Foi um total de {jogador["total"]} gols.')

Nome do jogador: Hélio
Quantas partidas Hélio jogou? 3
Quantos gols na partida 1? 4
Quantos gols na partida 2? 0
Quantos gols na partida 3? 1
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
{'nome': 'Hélio', 'gols': [4, 0, 1], 'total': 5}
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
O campo nome tem o valor Hélio
O campo gols tem o valor [4, 0, 1]
O campo total tem o valor 5
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
O jogador Hélio jogou 3 partidas.
  => Na partida 1, fez 4 gols.
  => Na partida 2, fez 0 gols.
  => Na partida 3, fez 1 gols.
Foi um total de 5 gols.


99. Crie um programa que leia nome, sexo e idade de várias pessoas, guardando os dados de cada pessoa em um dicionário e todos os dicionários em uma lista. No final, mostre:
- Quantas pessoas foram cadastradas
- A média de idade
- Uma lista com as mulheres
- Uma lista de pessoas com idade acima da média

In [29]:
pessoa = dict()
pessoas = list()
soma = 0

while True:
    pessoa['nome'] = str(input('Nome: ')).strip()
    
    while True:
        pessoa['sexo'] = str(input('Sexo [M/F]: ')).upper().strip()[0]
        if pessoa['sexo'] in 'MF':
            break
        print('ERRO! Por favor, digite apenas M ou F.')  
    
    pessoa['idade'] = int(input('Idade: '))
    soma += pessoa['idade']
    pessoas.append(pessoa.copy())
    
    while True:
        resp = str(input('Quer continuar? [S/N] ')).upper().strip()[0]
        if resp in 'SN':
            break
        print('ERRO! Por favor, digite apenas S ou N.')
    if resp == 'N':
        break

print('-='*30)
print(f'A) Ao todo temos {len(pessoas)} pessoas cadastradas.')

media = soma/len(pessoas) # soma das idades / qtd pessoas
print(f'B) A média de idade é de {media:5.2f} anos.')

print(f'C) As mulheres cadastradas foram ', end='')
for p in pessoas:
    if p['sexo'] == 'F':
        print(f'{n["nome"]} ', end='')
print()

print(f'D) Lista das pessoas que estão acima da média:')
for p in pessoas:
    if p['idade'] >= media:
        #print(f'nome = {p["nome"]}; sexo = {p["sexo"]}; idade = {p["idade"]}')
        for k, v in p.items(): # dicionários
            print(f'{k} = {v}; ', end='')
        print()
print('<< ENCERRADO >>')

Nome: Rafaela
Sexo [M/F]: n
ERRO! Por favor, digite apenas M ou F.
Sexo [M/F]: f
Idade: 22
Quer continuar? [S/N] s
Nome: Renato
Sexo [M/F]: g
ERRO! Por favor, digite apenas M ou F.
Sexo [M/F]: M
Idade: 34
Quer continuar? [S/N] a
ERRO! Por favor, digite apenas S ou N.
Quer continuar? [S/N] s
Nome: Bia
Sexo [M/F]: F
Idade: 34
Quer continuar? [S/N] s
Nome: Gustavo
Sexo [M/F]: M
Idade: 53
Quer continuar? [S/N] s
Nome: Lilian
Sexo [M/F]: F
Idade: 14
Quer continuar? [S/N] n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
A) Ao todo temos 5 pessoas cadastradas.
B) A média de idade é de 31.40 anos.
C) As mulheres cadastradas foram Rafaela Bia Lilian 
D) Lista das pessoas que estão acima da média:nome = Renato; sexo = M; idade = 34; 
nome = Bia; sexo = F; idade = 34; 
nome = Gustavo; sexo = M; idade = 53; 
<< ENCERRADO >>


100. Aprimore o exercício 98 para que ele funcione com vários jogadores, incluindo um sistema de visualização de detalhes do aproveitamento de cada jogador.

In [18]:
jogador = dict()
gols_nas_partidas = list()
time = list()

while True:
    jogador['nome'] = str(input('Nome do jogador: ')).strip()
    tot = int(input(f'Quantas partidas {jogador["nome"]} jogou? '))
    
    for g in range(0, tot):
        gols_nas_partidas.append(int(input(f'  Quantos gols na partida {g+1}? ')))
        
    jogador['gols'] = gols_nas_partidas[:]
    jogador['total'] = sum(partidas) #soma a lista
    time.append(jogador.copy())
    gols_nas_partidas.clear()
    
    while True:
        resp = str(input('Quer continuar? [S/N] ')).upper().strip()[0]
        if resp in 'SN':
            break
        print('ERRO! Por favor, digite S ou N.')
    if resp == 'N':
        break

print('-='*30)
print('cod ', end='')
for i in jogador.keys():
    print(f'{i:<15}', end='')
print()

print('-'*40)
for k, v in enumerate(time):
    print(f'{k:>3} ', end ='')
    for d in v.values():
        print(f'{str(d):<15}', end='')
    print()
print('-'*40)

print('-='*30)
while True:
    opc = int(input('Mostrar dados de qual jogador? (999 para parar) '))
    if opc == 999:
        break
    if opc >= len(time):
        print(f'ERRO! Não existe jogador com o código {opc}.')
    else:
        print(f' -- LEVANTAMENTO DO JOGADOR {time[opc]["nome"]}')
        for i, g in enumerate(time[opc]["gols"]):
            print(f'  No jogo {i+1} fez {g} gols.')
    print('-'*40)
print('<< VOLTE SEMPRE >>')

Nome do jogador: Hélio
Quantas partidas Hélio jogou? 2
  Quantos gols na partida 1? 1
  Quantos gols na partida 2? 2
Quer continuar? [S/N] s
Nome do jogador: Iago
Quantas partidas Iago jogou? 3
  Quantos gols na partida 1? 1
  Quantos gols na partida 2? 2
  Quantos gols na partida 3? 3
Quer continuar? [S/N] s
Nome do jogador: Ronaldo
Quantas partidas Ronaldo jogou? 4
  Quantos gols na partida 1? 0
  Quantos gols na partida 2? 0
  Quantos gols na partida 3? 2
  Quantos gols na partida 4? 1
Quer continuar? [S/N] s
Nome do jogador: Oswaldo
Quantas partidas Oswaldo jogou? 1
  Quantos gols na partida 1? 34
Quer continuar? [S/N] n
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
cod nome           gols           total          
----------------------------------------
  0 Hélio          [1, 2]         3              
  1 Iago           [1, 2, 3]      6              
  2 Ronaldo        [0, 0, 2, 1]   3              
  3 Oswaldo        [34]           34             
---------------

101. Faça um programa, utilizando dict comprehension, que gere um dicionário que relacione temperaturas em graus Celsius a Fahrenheit. Use as seguintes temperaturas em Celsius: 0, 10, 20, 30, 40.

In [4]:
tcelsius = [0, 10, 20, 30, 40]

celsius_para_fahrenheit = {f'{c}°C': f'{(c * 9/5) + 32}°F' for c in tcelsius}
print(celsius_para_fahrenheit)

{'0°C': '32.0°F', '10°C': '50.0°F', '20°C': '68.0°F', '30°C': '86.0°F', '40°C': '104.0°F'}


102. Em um arquivo chamado noticia.txt, escreva o seguinte título de matéria: Pessoas ainda não têm ‘devida maturidade’ para entender ChatGPT, diz professor da Uerj. Posteriormente, abra o arquivo novamente e acrescente o subtítulo: Para especialistas, ferramenta não tem capacidade de tirar empregos de advogados, jornalistas, entre outros profissionais. Por fim, mostre a leitura do arquivo em tela com uma frase em cada linha.

In [2]:
with open(file='noticia.txt', mode='w') as fp:
    titulo = "Pessoas ainda não têm ‘devida maturidade’ para entender ChatGPT, diz professor da Uerj" + '\n'
    fp.write(titulo)
    
with open(file='noticia.txt', mode='a') as fp:
    subtitulo = 'Para especialistas, ferramenta não tem capacidade de tirar empregos de advogados, jornalistas, entre outros profissionais'
    fp.write(subtitulo)
    
with open(file='noticia.txt', mode='r') as arquivo:
    conteudo = arquivo.read()
    
print(conteudo)

Pessoas ainda não têm ‘devida maturidade’ para entender ChatGPT, diz professor da Uerj
Para especialistas, ferramenta não tem capacidade de tirar empregos de advogados, jornalistas, entre outros profissionais


103. Faça um programa que leia o arquivo salarios2.csv e calcule a média e a mediana salarial dos funcionários.

Resposta: A média salarial dos funcionários é 79167.53 e a mediana é 83616.00

In [1]:
salarios = []

with open(file='salarios2.csv', mode='r', encoding='utf8') as arquivo:
    linha = arquivo.readline().strip() # lê cabeçalho
    linha = arquivo.readline().strip() # lê a primeira linha
    while linha:
        linha_separada = linha.split(',')
        salario = float(linha_separada[3])
        salarios.append(salario)
        linha = arquivo.readline().strip()


soma_total = sum(salarios)
quantidade = len(salarios)

media = soma_total/quantidade

salarios.sort() # ordena lista

if quantidade % 2 == 0:
    mediana = (salarios[quantidade/2 - 1] + salarios[quantidade/2])/2 # o índice começa de 0
else:
    mediana = salarios[quantidade // 2] # o índice começa de 0

print(f'A média salarial dos funcionários é ${media:.2f} e a mediana é ${mediana:.2f}')

A média salarial dos funcionários é $79167.53 e a mediana é $83616.00


104. Faça um programa que leia o arquivo salarios2.csv e armazene os cargos em uma lista. Depois percorra essa lista e armazene cargo e frequência (em que o cargo aparece na lista) em um dicionário. No final, mostre cargo e frequência dos 5 primeiros em ordem decrescente.

Dica 1: Se não souber ordenar um dicionário, use o ChatGPT. A função lambda é melhor explicada no notebook de funções.</br>
Dica 2: Você pode conferir sua resposta com os valores gerados usando o módulo Pandas no notebook de fundamentos (teórico)

In [10]:
cargos = []

with open(file='salarios2.csv', mode='r', encoding='utf8') as arquivo:
    linha = arquivo.readline().strip().split(',') # lê cabeçalho
    linha = arquivo.readline().strip() # lê a primeira linha
    while linha:
        linha_separada = linha.split(',')
        cargos.append(linha_separada[1])
        linha = arquivo.readline().strip()

cargos_distintos = set(cargos)
freq_cargos = {cargo: cargos.count(cargo) for cargo in cargos_distintos}

freq_ordenada = sorted(freq_cargos.items(), key=lambda cargo: cargo[1], reverse=True)
for i in range(5):
    print(f'\t{freq_ordenada[i][0]:<40} \t{freq_ordenada[i][1]:<5}')

	POLICE OFFICER                           	9489 
	FIREFIGHTER-EMT                          	1191 
	SERGEANT                                 	1138 
	FIREFIGHTER                              	970  
	POLICE OFFICER (ASSIGNED AS DETECTIVE)   	808  
